/*
 * Generated by KOFViewer.
 *
 * Researcher:  dmknght
 * Created 2026-09-22
 * Engine:      db format 8, module ABI 2
 */

/*
 * BillGates - the C++ DDoS bot also filed as Elknot and as ChinaZ.
 *
 * WHAT NAMES IT. The family carries its own class names in its RTTI, and they
 * are the reason it is called this:
 *
 *     CBillStatus   CUpdateBill   CUpdateGates   CThreadMonGates
 *     CThreadTaskGates   CAttackSyn   CAttackDns   CAttackAmp
 *     CThreadHttpGet   CThreadFakeDetect   CMiniHttpReq
 *
 * beside /usr/lib/libamplify.so, /tmp/notify.file, and a block of kernel
 * pktgen commands written through /proc/net/pktgen - which is how it sends at
 * line rate without going through a socket per packet.
 *
 *
 * WHY THE STRING SET AND NOT THE BLOCKS.
 *
 * Both were measured over 2669 samples this database did not already catch,
 * against 2213 clean objects. Block containment separated the generations from
 * each other - four clusters, none of which matched the others - and each
 * needed its own reference. The string set crossed them: one reference of
 * sixteen strings answers for all four.
 *
 *     blocks, per generation   83 + 36 + 34 + 29 = 182 samples, 4 rules
 *     strings, one reference   182 of those, and 35 more, in 1 rule
 *
 * Which is the property kofmod/kofsig.h states for this measure and the reason
 * it exists beside the block one: a rebuild for another target keeps almost
 * none of its code blocks and almost all of its strings.
 *
 * MEASURED at heuristic level 1, where this measure is gated:
 *
 *     VirusShare Linux, previously undetected    217 of 2669 objects
 *     /usr/bin + /usr/lib + static-linked clean    0 of 2213 objects
 *
 * SIXTEEN STRINGS AND SIXTY PER CENT, so ten of them have to be present. The
 * reference is deliberately not larger: strings shared by every generation are
 * what crosses them, and the rarer ones belong to one build each - taking
 * those would have written a rule about cluster 0 and called it a family.
 *
 * i386 in every sample measured, and the target says so rather than claiming
 * the family is: nothing here was measured on another architecture.
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofoverlord.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "BillGates");

KOF_TARGET_ARCH(KOF_ARCH_X86);

/* The author's strings of the samples above, after the static library was
 * cut - see koflib.h. Hashes and not the text: what is compared is WHICH
 * strings, never what they said. */
static const uint64_t ref_strings[] = {
	0x1362259d911c7bd1ull, 0x151d2cc5a799b303ull, 0x29a7b15aa34eebecull,
	0x2a0883e79a3c8a2aull, 0x32d4e25904c8d568ull, 0x3449925779a40626ull,
	0x8f179795f45696a0ull, 0x929ca6db3228a8a3ull, 0xa31fdfe6849bc55bull,
	0xb2180908ae86e244ull, 0xb44fc7685de18b11ull, 0xcdffc9cc174e6b4bull,
	0xce202cdad6da054cull, 0xdc878f53f206e236ull, 0xdf72701698d7cbffull,
	0xe227dda270c4c545ull
};

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_ovl_strings(ref_strings) >= 60u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
