/*
 * Generated by KOFViewer.
 *
 * Test sample: 50d7781fa1c1b916e0e9c328c6c5372abecb9a30c53e00f1e722c21c3c11bc88_detected_detected  sha256:50d7781fa1c1b916e0e9c328c6c5372abecb
 * Researcher:  dmknght
 * Created 2026-09-18, updated 2026-09-18
 * Engine:      db format 1.1, module ABI 2
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Gafgyt");

/* +0xf70e, 3409 bytes, 35 hash(es) */
KOF_PLAGUE_BLOCK(blk_3f33b152, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x0004689du, 0x00177341u, 0x001b11f2u, 0x00b2c19bu,
	0x00e3cd32u, 0x00edb544u, 0x00f92a57u, 0x013f24ecu,
	0x013f33e0u, 0x014e33d3u, 0x0155c1f6u, 0x019caa66u,
	0x01bb313bu, 0x01ccad6du, 0x02793f22u, 0x03a9948cu,
	0x03c45de5u, 0x03f2bbd1u, 0x03f8e6a8u, 0x0422a8bfu,
	0x0474f998u, 0x049364cdu, 0x0493fe59u, 0x04afb2e7u,
	0x054e9da4u, 0x0557cf38u, 0x056d09f1u, 0x05b42a78u,
	0x05bac7e6u, 0x05cd0fe8u, 0x063c1ff1u, 0x068d4385u,
	0x070be5edu, 0x0752c42eu, 0x07d2ed24u);

/* +0x11f9c, 2630 bytes, 39 hash(es) */
KOF_PLAGUE_BLOCK(blk_e2c7d50e, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x009bce6cu, 0x00d382c5u, 0x00d544afu, 0x011be008u,
	0x012239b3u, 0x01a2aa95u, 0x02233f9au, 0x02502d30u,
	0x02618f42u, 0x0291527fu, 0x02950fa6u, 0x02971d53u,
	0x02992c9eu, 0x02bd8751u, 0x02c34a2eu, 0x02d3c6b3u,
	0x02f6e623u, 0x0300130eu, 0x035b15f8u, 0x040c6909u,
	0x041097b7u, 0x04116688u, 0x041b9b9eu, 0x0484a1acu,
	0x04bccb31u, 0x04ed1b15u, 0x04f5a211u, 0x0548db62u,
	0x0587c82du, 0x0627bbd8u, 0x062d4aeau, 0x0646bedcu,
	0x06ed8f4du, 0x06fc460fu, 0x0781961cu, 0x07bb72e8u,
	0x07c66e80u, 0x07d62c40u, 0x07f14590u);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_3f33b152) >= 75u && kof_plague_score(blk_e2c7d50e) >= 60u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
