/*
 * Generated by KOFViewer.
 *
 * Test sample: 1fbfb2501ebe6e653d5e1e53b19f49eabbb34ed350615140097704539faacd0b_detected_detected  sha256:1fbfb2501ebe6e653d5e1e53b19f49eabbb3
 * Researcher:  dmknght
 * Created 2026-09-18, updated 2026-09-18
 * Engine:      db format 1.1, module ABI 2
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Gafgyt");

/* +0xb74e, 2048 bytes, 16 hash(es) */
KOF_PLAGUE_BLOCK(blk_6fad1193, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x0173ed42u, 0x018b1c13u, 0x01a2aa95u, 0x01ccad6du,
	0x02be5c01u, 0x03007469u, 0x03e2e629u, 0x03f2bbd1u,
	0x049ae098u, 0x04bccb31u, 0x04bced09u, 0x04ce9f18u,
	0x04e0c232u, 0x0548db62u, 0x06409544u, 0x071e2c02u);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_6fad1193) >= 60u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
