/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.cw-16d2453b795df99b13d6ccb38ad2aecc4959a3e2ab796e9c611a76b95deadd0c
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0xd000, 2828 bytes, 25 hash(es) */
KOF_PLAGUE_BLOCK(blk_23f254f1, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x000a58b5u, 0x00c5d4bfu, 0x00face72u, 0x010f0cecu,
	0x01451ff8u, 0x0172b62du, 0x01dcd60fu, 0x01fd8daau,
	0x0242595bu, 0x025513f5u, 0x0287945au, 0x0303fbdcu,
	0x03b900c7u, 0x03d7eb7au, 0x047e757bu, 0x04ad1505u,
	0x05487e31u, 0x05c9f4d5u, 0x060d03acu, 0x061831a1u,
	0x068e418eu, 0x06f111e5u, 0x072c924cu, 0x07356d0fu,
	0x07c4021bu);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_23f254f1) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
