/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Agent.ei-4a1c964410a1b276730da5718a1ee803aa813bfc69553bc6991da0ccffc201a3
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x8d98, 2064 bytes, 44 hash(es) */
KOF_PLAGUE_BLOCK(blk_41749021, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x003a99e5u, 0x0045466fu, 0x00653d7bu, 0x008fa51bu,
	0x0098a6e3u, 0x011b8affu, 0x012363e5u, 0x012cee32u,
	0x012f9c9fu, 0x0140a614u, 0x014d3ab7u, 0x01e61e24u,
	0x01f32a8eu, 0x02080eeau, 0x021db031u, 0x0226f253u,
	0x022ec9dau, 0x02488968u, 0x0251f6f1u, 0x02ab8645u,
	0x02d6ecefu, 0x03120e9du, 0x0381fa18u, 0x038ffd69u,
	0x03fb88c7u, 0x04143419u, 0x046821dau, 0x04a4ec1bu,
	0x04aee582u, 0x04c35e0fu, 0x04f1a127u, 0x05152390u,
	0x051ee812u, 0x052c8d0fu, 0x0549c9dfu, 0x056ce596u,
	0x0619e88eu, 0x064487b5u, 0x0722544du, 0x072d3e55u,
	0x073fbe68u, 0x07640b28u, 0x07b69ccau, 0x07f2cfa6u);

/* +0x95a8, 708 bytes, 17 hash(es) */
KOF_PLAGUE_BLOCK(blk_cc4cdd3d, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x0096800eu, 0x013f0d89u, 0x014d3ab7u, 0x0166848au,
	0x01a2aa95u, 0x02488968u, 0x027a3680u, 0x0285d010u,
	0x02d2bf75u, 0x02f34226u, 0x0313e35du, 0x04bccb31u,
	0x04fcf41du, 0x05478b7eu, 0x0580d158u, 0x06058fa2u,
	0x06f7d80cu);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_41749021) >= 70u && kof_plague_score(blk_cc4cdd3d) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
