/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.cw-3bcb6f628473f2e29ab7c10ef515482afa22432ce5b15693125a3ac9bb1114c6
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x15000, 4160 bytes, 84 hash(es) */
KOF_PLAGUE_BLOCK(blk_09bb9da8, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x001d2756u, 0x00228296u, 0x0027b18du, 0x00510681u,
	0x00662c94u, 0x00740792u, 0x008f8efeu, 0x00ccbc5du,
	0x00dfec28u, 0x00e34820u, 0x00f10b4fu, 0x010bbea5u,
	0x01129143u, 0x0181fe50u, 0x018a6032u, 0x01d4bf02u,
	0x01e042b5u, 0x01e8d5b0u, 0x02009719u, 0x0225b1c8u,
	0x02311adau, 0x023e4c90u, 0x02581f2du, 0x0268a9b5u,
	0x027c02fau, 0x0286b854u, 0x029710ffu, 0x02a6c9d9u,
	0x02b16f60u, 0x02c8a00bu, 0x02e49aebu, 0x02e76937u,
	0x02f51e48u, 0x0314a5d9u, 0x031b6d15u, 0x0324c6d0u,
	0x0341a989u, 0x036f8679u, 0x039ad925u, 0x03ded676u,
	0x040f19d1u, 0x044d34d0u, 0x04a0974au, 0x04db3d68u,
	0x0500f18du, 0x050a907au, 0x05121e63u, 0x05188e18u,
	0x051e1832u, 0x0598ba2fu, 0x059c4c89u, 0x05bdf124u,
	0x05c39270u, 0x05d6691fu, 0x05e23946u, 0x05f5733au,
	0x06064854u, 0x060a8b79u, 0x061c0cbbu, 0x061d6edbu,
	0x06258b4eu, 0x063525f7u, 0x063970dcu, 0x06765670u,
	0x068709a5u, 0x06925ec1u, 0x06a01963u, 0x06a545ccu,
	0x06a59136u, 0x06acdd4au, 0x06bd7d98u, 0x06d474d5u,
	0x0702d3fcu, 0x0706e305u, 0x070fc4a9u, 0x0713f0bbu,
	0x0718d0f8u, 0x07437174u, 0x0753c1cau, 0x07a11e90u,
	0x07a3e7a4u, 0x07a85e00u, 0x07b56ef5u, 0x07f42323u);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_09bb9da8) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
