/*
 * Generated by KOFViewer.
 *
 * Test sample: 8f656d525a5dee6314bca7a368bb184c9ef769c83ca2cdf07579584ec7166f9d_detected_detected
 * Researcher:  dmknght
 * Created 2026-09-20, updated 2026-09-20
 * Engine:      db format 1.1, module ABI 2
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>
#include <kofmod/kofoverlord.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x0, 75000 bytes, 128 hash(es) */
KOF_PLAGUE_BLOCK(blk_20a2ecee, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x0000f69bu, 0x00028edcu, 0x0003bc6eu, 0x00049576u,
	0x0005e6e9u, 0x00075320u, 0x0008b204u, 0x000a0a8du,
	0x000a1c58u, 0x000a58b5u, 0x000a9a94u, 0x000c5077u,
	0x000c96c1u, 0x000cf1aau, 0x000ddd64u, 0x000ebe8au,
	0x00105c38u, 0x001114dcu, 0x00112045u, 0x00152db2u,
	0x00155e06u, 0x00160019u, 0x00165bf0u, 0x00188b78u,
	0x0019bbf1u, 0x001acbe7u, 0x001b11f2u, 0x001b4b4bu,
	0x001d3e2eu, 0x001e09ccu, 0x0021240du, 0x0023bd80u,
	0x0024995cu, 0x0027e4e7u, 0x002aa7c9u, 0x002ca497u,
	0x002e9a76u, 0x003279c0u, 0x003651c9u, 0x003693f8u,
	0x0036f53bu, 0x0037bf66u, 0x0037eed7u, 0x00398294u,
	0x003a1ed0u, 0x003a41aau, 0x003ad588u, 0x003b231au,
	0x003bba4au, 0x003bd375u, 0x003c9919u, 0x003ea6d2u,
	0x003f88c8u, 0x003f9b1du, 0x0040d8cfu, 0x0041da4bu,
	0x0041dcefu, 0x00437e6bu, 0x0044390fu, 0x0047683eu,
	0x0048228du, 0x0049cb77u, 0x004a23cfu, 0x004cbbb8u,
	0x004cfb88u, 0x004d41f8u, 0x004d64dau, 0x004da37cu,
	0x004f29c4u, 0x00503459u, 0x0052a91du, 0x0052cddbu,
	0x0053cd80u, 0x0054922fu, 0x0055a50bu, 0x0055ba05u,
	0x0056de7bu, 0x00579f7bu, 0x00599118u, 0x0059f997u,
	0x005aebe5u, 0x005c518au, 0x005ce91eu, 0x005d8328u,
	0x005f9a49u, 0x00604eb4u, 0x00622eadu, 0x0062f33bu,
	0x00635436u, 0x00635934u, 0x006369cbu, 0x0064ca12u,
	0x0065dff7u, 0x00677eb3u, 0x0068d250u, 0x00699cc7u,
	0x006a8f37u, 0x006b06bau, 0x006bfdabu, 0x006c325fu,
	0x006cd101u, 0x007103f5u, 0x0072130cu, 0x00735e3fu,
	0x00737581u, 0x0073fe3bu, 0x0074a98fu, 0x007671c0u,
	0x0078777fu, 0x00793a32u, 0x007c7545u, 0x007c8dfcu,
	0x007d731eu, 0x007d9750u, 0x007dc2c6u, 0x00800c10u,
	0x00803747u, 0x0080a854u, 0x0080ee72u, 0x00824865u,
	0x0082b58du, 0x0083bdbfu, 0x0085b5abu, 0x0085c5c7u,
	0x00864f44u, 0x008830b3u, 0x0088b5bdu, 0x00896882u);

/* The shape of the sample above: what the builder produced, not what it says. */
static const struct kof_ovl_shape ref_shape = {
	.fsize    = 105097ull,
	.ptypes   = 0x00000002u,
	.etype    = 2u,
	.cls      = 2u,
	.end      = 1u,
	.n_region = 2u,
	.region_fsz = { 75000ull, 1744ull },
	.region_x   = { 1u, 0u }
};

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_20a2ecee) >= 50u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
	if (kof_ovl_shape(ref_shape) >= 70u)
		KOF_SCAN_SUSPECT(KOF_MALVAR_AUTO);
}
