/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.mr-875dacb6ed5f9e4484c0abf13c4c58c11d707f90554a8514aac3a54644cb1d2c
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x54000, 4160 bytes, 89 hash(es) */
KOF_PLAGUE_BLOCK(blk_f7ab9507, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x00102d31u, 0x0039d989u, 0x0048a819u, 0x004c1344u,
	0x004dee4au, 0x005ad286u, 0x009b12ecu, 0x00a15607u,
	0x00c1e497u, 0x00dffacdu, 0x00e0229bu, 0x00e86940u,
	0x013060c6u, 0x0131762au, 0x0151f095u, 0x01715336u,
	0x01769199u, 0x01a2b02bu, 0x01b6185fu, 0x01ba3a48u,
	0x01c1f7bcu, 0x01c832d6u, 0x0204ce09u, 0x02122725u,
	0x021a71edu, 0x022dd49eu, 0x0233a8d9u, 0x023ccc81u,
	0x023ececcu, 0x0243d088u, 0x025dc072u, 0x02c366f3u,
	0x02ca1c02u, 0x02eba74fu, 0x033735a1u, 0x033a6d81u,
	0x03404317u, 0x034b73a3u, 0x035325ebu, 0x037c018eu,
	0x038291edu, 0x03895bd5u, 0x0397a579u, 0x03a9a82fu,
	0x03ca1b9du, 0x03d945fau, 0x03de833bu, 0x03e91eefu,
	0x03ea9eabu, 0x04032aaau, 0x042dfcc1u, 0x0432483eu,
	0x044076abu, 0x0450c838u, 0x04aa8a2cu, 0x04b1899au,
	0x04b3d855u, 0x04b8ed12u, 0x04cdcfebu, 0x0502bbb2u,
	0x05031794u, 0x05267503u, 0x052dd19du, 0x0539bb6du,
	0x057e9c94u, 0x059d087bu, 0x05a05e66u, 0x05cd5bfcu,
	0x05f1a614u, 0x0614a31bu, 0x061b385du, 0x0631c6d1u,
	0x069010f6u, 0x06a51e3au, 0x06b18590u, 0x06caa56eu,
	0x06e00c84u, 0x06f78a79u, 0x06f83c9du, 0x0733c58cu,
	0x07355d84u, 0x075d61b0u, 0x075e4a02u, 0x077ce83au,
	0x07ad7873u, 0x07c6dd41u, 0x07d481f4u, 0x07f772ffu,
	0x07fd908au);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_f7ab9507) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
