/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Gafgyt.jk-4b53589aa2d15bbd5e723d2ec61a9453edcd3dfd5d82cee356c5388f7d37aadd
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x15000, 4160 bytes, 88 hash(es) */
KOF_PLAGUE_BLOCK(blk_bc33f716, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x00111b48u, 0x00363e80u, 0x005ebccbu, 0x0074a4dbu,
	0x00dcec1du, 0x00e51bddu, 0x00ef95ccu, 0x011fb2b6u,
	0x013f24ecu, 0x013f33e0u, 0x015b990fu, 0x0187ebb3u,
	0x018a727bu, 0x01c9c861u, 0x01ccad6du, 0x01d4cea0u,
	0x0201e766u, 0x021efd8au, 0x022b93ceu, 0x023601e8u,
	0x023e4479u, 0x026f7af2u, 0x02793f22u, 0x028f9f0cu,
	0x02b5ab5fu, 0x02bc8bd3u, 0x02d96d36u, 0x02e87f5cu,
	0x02ee8fdcu, 0x031301cdu, 0x03188062u, 0x032f11e5u,
	0x0342ad34u, 0x03463838u, 0x035c34f9u, 0x036587c2u,
	0x038f1a7au, 0x03927a92u, 0x03944484u, 0x03afa1a5u,
	0x03ba1828u, 0x03c52802u, 0x03db3bbfu, 0x03e01767u,
	0x03f2bbd1u, 0x045ace9au, 0x047b821fu, 0x0481bf29u,
	0x0491a800u, 0x04964c36u, 0x049f5faau, 0x04a1ac33u,
	0x04bccb31u, 0x04ea90aau, 0x05161e88u, 0x05175a17u,
	0x0535792du, 0x0542f597u, 0x056ac829u, 0x0580f6b4u,
	0x05943dceu, 0x0598be19u, 0x05acf712u, 0x05ae6e35u,
	0x05b430d4u, 0x05b735bfu, 0x05c8cdd7u, 0x05f86584u,
	0x05fa065bu, 0x0613fec9u, 0x065ac164u, 0x0680bd38u,
	0x068c76cdu, 0x06b15017u, 0x06e10fdau, 0x06f7a51fu,
	0x06f8ae2eu, 0x06fb8cafu, 0x06fe854fu, 0x075188f7u,
	0x07860cb7u, 0x07ab26e0u, 0x07c03406u, 0x07cf94cfu,
	0x07cff25cu, 0x07dc30e2u, 0x07e16e4fu, 0x07f57dcdu);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_bc33f716) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
