/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.b-6c6b11bd7a1efffc4de087e89bf657934ba0f3592a7ad06e750bd85333e19466
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x1b000, 2709 bytes, 58 hash(es) */
KOF_PLAGUE_BLOCK(blk_02239100, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x000a58b5u, 0x00337f15u, 0x004f29c4u, 0x0059873au,
	0x005dc806u, 0x006afacbu, 0x00c5d4bfu, 0x00e01b86u,
	0x013d9b13u, 0x0140a614u, 0x01488073u, 0x014d3ab7u,
	0x0152b725u, 0x016cc914u, 0x018bdd8au, 0x01a79b4bu,
	0x01b93848u, 0x01c8d1ecu, 0x01dcd60fu, 0x01fd1809u,
	0x02291bc1u, 0x022b93ceu, 0x0248602au, 0x02488968u,
	0x024e727cu, 0x0251eac4u, 0x0283f384u, 0x02b2ef18u,
	0x0314d91bu, 0x0316346au, 0x0342ad34u, 0x03463838u,
	0x034e72a9u, 0x035c34f9u, 0x03944484u, 0x03a7247cu,
	0x03af56ffu, 0x03afa1a5u, 0x03ba1828u, 0x03fd6a1bu,
	0x040f83d1u, 0x0423d258u, 0x046f2e36u, 0x047b229fu,
	0x04967131u, 0x04b5ef44u, 0x04cc89cfu, 0x0515e1f6u,
	0x0535792du, 0x054afb41u, 0x0598be19u, 0x05fbe3b3u,
	0x066e20c2u, 0x06d69917u, 0x070c7073u, 0x07131227u,
	0x072687bcu, 0x07cf94cfu);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_02239100) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
