/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.lb-b62c9b53bac6aeb692dddf05329cd07702d2465d91ff38b9bd405e28bdcbc448
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0xf000, 3387 bytes, 87 hash(es) */
KOF_PLAGUE_BLOCK(blk_c3db6596, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x00082140u, 0x000a58b5u, 0x001b6c53u, 0x0038dea6u,
	0x00481193u, 0x004f29c4u, 0x0059873au, 0x005e2461u,
	0x00654a88u, 0x00c317e0u, 0x00c5d4bfu, 0x00e01b86u,
	0x00e49fa6u, 0x00f5699du, 0x013e232bu, 0x0146afdeu,
	0x01488073u, 0x0152b725u, 0x01534c97u, 0x016c77c0u,
	0x018ead1fu, 0x01a9854au, 0x01dcd60fu, 0x0204efa3u,
	0x021e4834u, 0x02291bc1u, 0x02488968u, 0x028f4bc2u,
	0x02b2ef18u, 0x02f74b65u, 0x0314d91bu, 0x0316346au,
	0x0342ad34u, 0x0343ccb4u, 0x035c34f9u, 0x03977146u,
	0x03a7247cu, 0x03af56ffu, 0x03afa1a5u, 0x03b6c698u,
	0x03b6f8c7u, 0x03bef497u, 0x03db3bbfu, 0x03ee2f36u,
	0x03fd1a0du, 0x03fd6a1bu, 0x040f83d1u, 0x0418c303u,
	0x0423d258u, 0x04390a82u, 0x046f0858u, 0x047166cbu,
	0x047b229fu, 0x0482d2edu, 0x04b5ef44u, 0x04bca4c4u,
	0x04bccb31u, 0x04fcf41du, 0x050cba0fu, 0x0515e1f6u,
	0x0533c72bu, 0x0535792du, 0x0544dbdcu, 0x05487e31u,
	0x0598be19u, 0x05c38192u, 0x05d38928u, 0x0603743cu,
	0x060eae28u, 0x06113a96u, 0x06137df8u, 0x061831a1u,
	0x06240f90u, 0x063d9ffcu, 0x066e20c2u, 0x0680bd38u,
	0x069f9183u, 0x06ab141cu, 0x06d69917u, 0x070c7073u,
	0x07131227u, 0x0779778au, 0x07968b1au, 0x0799cf3bu,
	0x07af7645u, 0x07bd21d3u, 0x07cf94cfu);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_c3db6596) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
