/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.mp-ed458b0f45dad79a7469892fe54fd6f465aea793ae9ddcb6a602d7dc8b5cf044
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x14000, 2043 bytes, 37 hash(es) */
KOF_PLAGUE_BLOCK(blk_008700e3, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x002e40ecu, 0x0067db73u, 0x00b46f1cu, 0x00bb7713u,
	0x00d3214fu, 0x00d449dbu, 0x01689324u, 0x01898653u,
	0x018ff4c8u, 0x01a5a86fu, 0x01a8deeeu, 0x02911a0bu,
	0x02b2ef18u, 0x02c58032u, 0x031a956bu, 0x0334317du,
	0x03355ed2u, 0x0342ad34u, 0x039aaa03u, 0x03d27e2cu,
	0x03edc9dau, 0x041e066cu, 0x0434bc8bu, 0x047b229fu,
	0x04929a06u, 0x049d7ff0u, 0x04f94e31u, 0x04fe154fu,
	0x055c40a7u, 0x05688775u, 0x057bef2bu, 0x05d3e7a9u,
	0x06a1f17cu, 0x06a243a5u, 0x06c345ecu, 0x0701acb3u,
	0x07675979u);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_008700e3) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
