/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.ba-12d1a642174b1c538eae7a2b506a563bde1ba3c061b5781212c2e3022e4d014e
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0xf000, 3009 bytes, 84 hash(es) */
KOF_PLAGUE_BLOCK(blk_9d1937b8, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x0001ec82u, 0x000365d3u, 0x000a9a94u, 0x003a99e5u,
	0x004f29c4u, 0x0059873au, 0x005d0cffu, 0x008f348cu,
	0x00a958e0u, 0x00ca05ceu, 0x00e01b86u, 0x01174d62u,
	0x0127cc23u, 0x012c1bf7u, 0x01488073u, 0x01524461u,
	0x0152b725u, 0x0154dbeau, 0x01680682u, 0x0170b25du,
	0x01a4dffdu, 0x01c5ae1du, 0x021e8c89u, 0x02291bc1u,
	0x023bfd60u, 0x02488968u, 0x026349c5u, 0x026d0b75u,
	0x029d066fu, 0x02b2ef18u, 0x02cb67f9u, 0x030f20a1u,
	0x0314d91bu, 0x0316346au, 0x0334ddd1u, 0x0342ad34u,
	0x0343ccb4u, 0x0353d3edu, 0x0358e150u, 0x0371a72au,
	0x03a7247cu, 0x03af56ffu, 0x03afa1a5u, 0x03b1d0e6u,
	0x03e6fdc1u, 0x03fd6a1bu, 0x040f83d1u, 0x0418c303u,
	0x0423d258u, 0x047b229fu, 0x047fe191u, 0x04a4d534u,
	0x04b5ef44u, 0x0511bde6u, 0x0513557fu, 0x0515e1f6u,
	0x0536747bu, 0x05487e31u, 0x057fcc91u, 0x0598be19u,
	0x0632131eu, 0x063a0696u, 0x06443150u, 0x064487b5u,
	0x0644caa0u, 0x06644723u, 0x06687a7cu, 0x066e20c2u,
	0x067e9c81u, 0x06893a96u, 0x06bb3b42u, 0x06c3011eu,
	0x06cb065au, 0x06d69917u, 0x06e11cf9u, 0x070c7073u,
	0x07131227u, 0x071c802eu, 0x07238aebu, 0x07242ebau,
	0x07341817u, 0x07ba40f1u, 0x07cf94cfu, 0x07f7fca6u);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_9d1937b8) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
