/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.gen-99890bb10d0cb653b009770c5fe1aeb24cd394ede9623a1463b46dc01e8d8b9f
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0xe000, 4160 bytes, 84 hash(es) */
KOF_PLAGUE_BLOCK(blk_8443c355, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x001200a5u, 0x003316ddu, 0x005e33f8u, 0x006587bau,
	0x0069d5a6u, 0x0075eb22u, 0x007a8d30u, 0x00911c67u,
	0x00a79916u, 0x00c07d7au, 0x00d2ac2du, 0x00d58521u,
	0x00df2b42u, 0x00e719c0u, 0x00f3a66cu, 0x0115dbc5u,
	0x012c85d4u, 0x0148ba40u, 0x015c6b03u, 0x0172e08eu,
	0x018a0a5fu, 0x019f5ec3u, 0x01a84776u, 0x01e0ed7bu,
	0x01e23428u, 0x01ff357cu, 0x0226dcceu, 0x02287309u,
	0x022d2128u, 0x023a7a18u, 0x024ae3f1u, 0x026a74acu,
	0x026f06e4u, 0x02a52792u, 0x02ddb520u, 0x02e9cd90u,
	0x02f55b8bu, 0x0304fd96u, 0x031364f6u, 0x031d3020u,
	0x0346660cu, 0x03469b03u, 0x03983b99u, 0x0399d6edu,
	0x03b114f0u, 0x03da376cu, 0x040f8dd7u, 0x0432946au,
	0x044123ecu, 0x045a1a56u, 0x047577afu, 0x049eb1a7u,
	0x049f5faau, 0x04b656a6u, 0x04cb9b7bu, 0x0508a12cu,
	0x0509321au, 0x051e579eu, 0x053fcfdfu, 0x05487e31u,
	0x0593b5e7u, 0x059a9fdeu, 0x059e79b2u, 0x05b381aau,
	0x061986ecu, 0x06403be4u, 0x0641615cu, 0x064e5c9fu,
	0x0654c206u, 0x066c5eeeu, 0x068265f5u, 0x06bd43c8u,
	0x06c5320du, 0x06dd5241u, 0x06fbdf0au, 0x070c3413u,
	0x070d86f2u, 0x074ba438u, 0x0784a05au, 0x07b5dc1bu,
	0x07bdcf99u, 0x07c2a73eu, 0x07d1f969u, 0x07d510c1u);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_8443c355) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
