/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.b-b00dd207b70c2e6593aa6797d94cf023b41c5755da93787830dc15b383675b24
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x10000, 4160 bytes, 64 hash(es) */
KOF_PLAGUE_BLOCK(blk_bd657029, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x000a58b5u, 0x0015cd18u, 0x002e0d1bu, 0x003cf017u,
	0x004ef529u, 0x0092b5a4u, 0x009575c0u, 0x00b15217u,
	0x00c07d7au, 0x00c5d4bfu, 0x00e3cd32u, 0x01268a93u,
	0x0133da5au, 0x013f24ecu, 0x014d3ab7u, 0x01951a79u,
	0x01bb313bu, 0x01ccad6du, 0x01dcd60fu, 0x01fa6783u,
	0x021db031u, 0x0243d200u, 0x024b948bu, 0x02793f22u,
	0x0284d41du, 0x02b2ef18u, 0x02b819eau, 0x02f74b65u,
	0x030f3c18u, 0x0342ad34u, 0x035c34f9u, 0x03af56ffu,
	0x03afa1a5u, 0x03d443ecu, 0x03e01767u, 0x03e429c1u,
	0x03f2bbd1u, 0x03f2ff95u, 0x03ff5638u, 0x0418f8c5u,
	0x0439bd05u, 0x04dde3dbu, 0x04e2c5e5u, 0x0535792du,
	0x05487e31u, 0x056a2d03u, 0x057807e8u, 0x0598be19u,
	0x05d42a12u, 0x05d93a49u, 0x05e51755u, 0x05e6a01du,
	0x063d92f3u, 0x067c0758u, 0x06ee363fu, 0x06f11dbfu,
	0x073fbe68u, 0x0767753fu, 0x077d04d7u, 0x0798b271u,
	0x07a25b25u, 0x07cf94cfu, 0x07cff07bu, 0x07e6a4f9u);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_bd657029) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
