/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.h-77b199ce132fa548e4ac57f8ef90beafe4c619b3257d1c0ca12a1ac414ecf0f1
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x4000, 1683 bytes, 58 hash(es) */
KOF_PLAGUE_BLOCK(blk_7b73e872, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x002dcb35u, 0x00652344u, 0x007474dbu, 0x008de5f9u,
	0x00aec952u, 0x00b1ed89u, 0x00d57e70u, 0x00d92164u,
	0x0159410eu, 0x017e65a8u, 0x01805f39u, 0x0190c9adu,
	0x01aba625u, 0x01ad61c6u, 0x01b18abau, 0x020f534eu,
	0x02178a9du, 0x022800eeu, 0x025ff8a2u, 0x027ad6f0u,
	0x028a8fa2u, 0x02c24922u, 0x02e7415bu, 0x02edf59eu,
	0x030d3f6du, 0x033e3822u, 0x03aac274u, 0x0411af92u,
	0x043c79e4u, 0x0471edbeu, 0x049d89aeu, 0x04d033b4u,
	0x05212483u, 0x05585ee7u, 0x05599615u, 0x05a936b5u,
	0x05ac9cfdu, 0x05cc0176u, 0x05e32824u, 0x05f25e25u,
	0x05f6a724u, 0x065a890bu, 0x067e60bbu, 0x06960e57u,
	0x069d2f8du, 0x06ad979au, 0x06b28d4du, 0x06ececa3u,
	0x070bdab9u, 0x070e46d9u, 0x07152f08u, 0x07168d8fu,
	0x071972f4u, 0x0721ada1u, 0x0727add6u, 0x079b8f88u,
	0x07ae65d6u, 0x07c6005au);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_7b73e872) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
