/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.mp-f3c0f212bf355c64b118fe3f90a581229085c1554b1ee4a70cc36784db6add4d
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x1000, 4160 bytes, 85 hash(es) */
KOF_PLAGUE_BLOCK(blk_cc895346, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x0015ca0fu, 0x00228e66u, 0x00269b76u, 0x00278de6u,
	0x002eea5cu, 0x00801b14u, 0x0085677cu, 0x0097f722u,
	0x009f1fccu, 0x00bfdfd1u, 0x01048047u, 0x015f5f88u,
	0x01623cd2u, 0x0176c7d5u, 0x017f358fu, 0x019da1bcu,
	0x01c20976u, 0x01cc0c7au, 0x01ece56bu, 0x01eeaf70u,
	0x02206d30u, 0x0226693cu, 0x02291653u, 0x023d3dd1u,
	0x02549b0fu, 0x025a8a15u, 0x029c0c57u, 0x02ad29dbu,
	0x02f74179u, 0x02fc2408u, 0x02fcb14du, 0x0305ed2bu,
	0x0324108eu, 0x034e72cau, 0x035a4cb5u, 0x03748da3u,
	0x0378baedu, 0x03998498u, 0x039fab5au, 0x03a45d61u,
	0x03a6c411u, 0x03cd9302u, 0x03f1014du, 0x040430f9u,
	0x040caa1bu, 0x044d317eu, 0x04536c28u, 0x0478f2a1u,
	0x047b60f5u, 0x054b69a2u, 0x0554fde8u, 0x0557a677u,
	0x0558328au, 0x05628a00u, 0x05abca9eu, 0x05c2d675u,
	0x05c8434fu, 0x05cefedau, 0x05d1038du, 0x05ee2f68u,
	0x05f121fdu, 0x0603d322u, 0x060c9e20u, 0x0612d695u,
	0x06260083u, 0x063bdea2u, 0x06415258u, 0x064ba128u,
	0x065d0de8u, 0x068788c9u, 0x06a1a3d2u, 0x06b5ca17u,
	0x06c56647u, 0x06e83262u, 0x06fa69acu, 0x06fef404u,
	0x070ae65du, 0x072b86c9u, 0x074f6155u, 0x075d6538u,
	0x077f7d77u, 0x07a7ba00u, 0x07c5b0afu, 0x07d7850eu,
	0x07ff4a9au);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_cc895346) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
