/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.mj-7b50e4b46def7510b0adcf2a30c354c5641de17e89f3b60e4fc920c9f632945b
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0xd000, 4160 bytes, 83 hash(es) */
KOF_PLAGUE_BLOCK(blk_2845bfaf, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x0001a784u, 0x0003fe37u, 0x001b11f2u, 0x003f4711u,
	0x006bafa4u, 0x0143fa84u, 0x01458410u, 0x014e33d3u,
	0x0155c1f6u, 0x019caa66u, 0x01a992f5u, 0x01b1512bu,
	0x01bb313bu, 0x01c9c861u, 0x01ccad6du, 0x0201436au,
	0x021efd8au, 0x025be912u, 0x0287945au, 0x0290cad7u,
	0x02ae3fc4u, 0x02d26a19u, 0x02d96d36u, 0x02e98e42u,
	0x02ee8fdcu, 0x02fc68a8u, 0x030562cdu, 0x031364f6u,
	0x0313c207u, 0x032f98f8u, 0x033b2000u, 0x0341e1a7u,
	0x035b2621u, 0x0381fe4cu, 0x038c433au, 0x03927a92u,
	0x03957f84u, 0x039fa4efu, 0x03b65e44u, 0x03c45de5u,
	0x03c52802u, 0x03db3bbfu, 0x03e01767u, 0x03ea0bf5u,
	0x03f2bbd1u, 0x0422a8bfu, 0x042742c9u, 0x043cd6dbu,
	0x0493fe59u, 0x049d3ed2u, 0x049f5faau, 0x04a1ac33u,
	0x04ac8367u, 0x04bccb31u, 0x04c705fcu, 0x05031163u,
	0x052ac93fu, 0x05487e31u, 0x056d09f1u, 0x0587b760u,
	0x058a6578u, 0x058bdd85u, 0x05979628u, 0x05aab7c8u,
	0x05acf712u, 0x05bab446u, 0x05ef7aacu, 0x05fa065bu,
	0x063c1ff1u, 0x06736a02u, 0x0680bd38u, 0x068d4385u,
	0x069b2b1eu, 0x06b86e0au, 0x06c3a9aau, 0x070063fau,
	0x07138c03u, 0x072332d2u, 0x077b5c4du, 0x078f3d35u,
	0x07ad3a9eu, 0x07cff25cu, 0x07dc30e2u);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_2845bfaf) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
