/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.mw-83abdb13cedfd71e237b3ecb2ce8d88d0160098a0a3cefd5750c1d3412e69ae3
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x8000, 1574 bytes, 44 hash(es) */
KOF_PLAGUE_BLOCK(blk_fa5f72ef, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x00719c9fu, 0x00ac9dc3u, 0x00bb6990u, 0x00ddc4f6u,
	0x00e68ef8u, 0x012867d5u, 0x012fc7e7u, 0x0162aeccu,
	0x01a92125u, 0x01c3ef60u, 0x01f43511u, 0x02140ad8u,
	0x0226443eu, 0x0237b05au, 0x0262aeedu, 0x02a078b3u,
	0x0312fc5au, 0x031c487au, 0x0331afeau, 0x0380c886u,
	0x03e8bdb9u, 0x047d4e4fu, 0x047f00cbu, 0x04a37359u,
	0x04bdf9a2u, 0x04c46375u, 0x04db2434u, 0x051d0158u,
	0x055e195bu, 0x05a51ad0u, 0x05bf88c3u, 0x05e40d50u,
	0x060510f7u, 0x0616ada6u, 0x0675dc16u, 0x0687aa9eu,
	0x06e88512u, 0x06fc40dbu, 0x073684f4u, 0x075ad1a8u,
	0x077ae65au, 0x0789b7d6u, 0x07a9bf90u, 0x07d5b51cu);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_fa5f72ef) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
