/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.cw-f3d0782a39ee28ddb743a20695b14e8e8ab8801d95fdb534fdd2d87b2c8b202b
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x12000, 4160 bytes, 85 hash(es) */
KOF_PLAGUE_BLOCK(blk_a5cf6d4a, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x00c07d7au, 0x00c8f8a1u, 0x00d6cddau, 0x00f514d5u,
	0x00f8ee66u, 0x00face72u, 0x00fc89bbu, 0x01064910u,
	0x013e7d89u, 0x01451ff8u, 0x014a5f6eu, 0x017fa33cu,
	0x018b1c13u, 0x018f0849u, 0x01951a79u, 0x01d766feu,
	0x01e28f96u, 0x0242595bu, 0x0249f1dau, 0x024b948bu,
	0x026bffa6u, 0x027f283eu, 0x0287945au, 0x0292ddacu,
	0x02ad5180u, 0x02e65c63u, 0x0303fbdcu, 0x030a865au,
	0x030a87d8u, 0x032c11a8u, 0x033217cfu, 0x03b02656u,
	0x03b17e6bu, 0x03cabfecu, 0x03ce4386u, 0x03dda16du,
	0x03e41075u, 0x03fa8aadu, 0x04169a3du, 0x0479338au,
	0x049efe43u, 0x04ad1505u, 0x04bd4c4au, 0x04c36e80u,
	0x04cb9b7bu, 0x04e402feu, 0x0529773du, 0x052e9801u,
	0x05374c69u, 0x05468159u, 0x0552e7bau, 0x056181efu,
	0x057e5c10u, 0x05843601u, 0x058e34d9u, 0x059a2928u,
	0x05ae7c98u, 0x05c03111u, 0x05dae4fdu, 0x05de8b01u,
	0x060d922eu, 0x0626103du, 0x0661321fu, 0x06ae0db7u,
	0x06ae23a7u, 0x06cc1237u, 0x06cfa553u, 0x06ed01e5u,
	0x06f111e5u, 0x070f918du, 0x071a019cu, 0x07283d21u,
	0x072c924cu, 0x0731a422u, 0x07356d0fu, 0x073632deu,
	0x073fbe68u, 0x07950cceu, 0x07a25b25u, 0x07b9d270u,
	0x07c4021bu, 0x07da7c03u, 0x07e7fc79u, 0x07ef700fu,
	0x07fbbcf2u);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_a5cf6d4a) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
