/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Gafgyt.dd-8417d0598f57edbfde6ee293791c45d4cf8b35cbfb7f9dcf74d2a71651eb34d8
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0xf000, 4160 bytes, 25 hash(es) */
KOF_PLAGUE_BLOCK(blk_cec31947, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x00052d89u, 0x0087b48cu, 0x01742a5du, 0x018e9b1fu,
	0x01a12e67u, 0x01ab0775u, 0x01ccad6du, 0x0294161bu,
	0x0298db25u, 0x029a5c8du, 0x030038b1u, 0x03231de4u,
	0x03d7eb7au, 0x03e2e629u, 0x03f5ac08u, 0x049ae098u,
	0x04ce8230u, 0x04e21c5eu, 0x04f6993cu, 0x0579dc66u,
	0x05881c41u, 0x058df270u, 0x06af6389u, 0x06fbe4b6u,
	0x0709eaefu);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_cec31947) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
