/*
 * Generated by KOFViewer.
 *
 * Researcher:  dmknght
 * Created 2026-09-22
 * Engine:      db format 8, module ABI 2
 */

/*
 * RST, build A - the /~telcom69/ command channel.
 *
 * WHAT THE FAMILY DOES TO A FILE. The payload is APPENDED and the entry point
 * redirected into it; the host is whatever executable was to hand. Measured
 * here: the entry lies outside every PROGBITS section in 24 of 25 samples,
 * and the hosts are named, httpd, login, sendmail, an IRC client, a flooder -
 * sizes from 8.5 KB to 583 KB. Only two of the sixty-two are themselves
 * flooders, which is why this is not filed under that family.
 *
 * ONE RULE PER BUILD, and rst_01.c is the other. They share a family and not
 * a payload: block containment between the two has a median of 8-9% and
 * string containment a median of 3%, so one rule for both would have been one
 * rule for neither.
 *
 *
 * THE BLOCK IS THE DETECTION; THE STRINGS ARE THE SECOND WAY IN.
 *
 * The strings look like perfect signatures and are not durable: both are on
 * the AUTHOR'S side of the wire - their host, their path - so both are theirs
 * to change, and a rule made only of them dates to one campaign. The
 * payload's CODE is what they would have to rewrite. Both are kept because
 * they answer on different samples and neither costs the other anything.
 *
 * CUT FROM THE PAYLOAD IN REGION COORDINATES, which cost a revision to learn:
 * a block declares a region and the matcher keeps the k smallest hashes OF
 * THAT REGION, so a span taken at a file offset that straddles the boundary
 * hashes bytes the matcher never reads. The first attempt scored 4% on the
 * very sample it was cut from.
 *
 * MEASURED: block score min 50, median 80 across the samples that fire;
 * 0 of 13159 clean objects in /usr/bin and /usr/lib. Forty, so the weakest
 * measured sample has ten points under it.
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_VIRUS, "RST");

KOF_TARGET_ARCH(KOF_ARCH_X86);

/* The payload is appended, so parts of it fall outside every section the file
 * declares - a range of CODE|DATA found one string of two and the rule never
 * fired. */
KOF_TARGET_RANGE(scan_range_all, KOF_SCAN_ELF_CODE | KOF_SCAN_ELF_DATA |
				 KOF_SCAN_ELF_NOLOAD | KOF_SCAN_ELF_UNCLAIMED);

KOF_DEFINE_STR(s0, "GET /~telcom69/gov.php HTTP/1.0", KOF_CASE_EXACT,
	       KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "/dev/hdx", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

KOF_PLAGUE_BLOCK(blk_7af46712, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x0009143fu, 0x000a4f10u, 0x0015d25cu, 0x002b8afbu,
	0x004c509au, 0x0090b33bu, 0x00ade854u, 0x00be6f2au,
	0x00c83e6du, 0x00deccacu, 0x00f18cfau, 0x00f1a3d4u,
	0x00fd8bf7u, 0x01179faau, 0x012cb8f3u, 0x01409f1du,
	0x01451ff8u, 0x01561371u, 0x015a9001u, 0x015e1c3fu,
	0x0185afb9u, 0x01900b2du, 0x01adc1e5u, 0x01cc19f5u,
	0x01e0b732u, 0x01e5000bu, 0x01e892bdu, 0x01fc8c39u,
	0x01fd8daau, 0x0202ce9du, 0x0209f239u, 0x02165d85u,
	0x024a7344u, 0x0288af4au, 0x02cd5c09u, 0x02cda938u,
	0x02d8212bu, 0x02edcf63u, 0x02fca4bfu, 0x030c81d6u,
	0x030d41deu, 0x031422b3u, 0x03156a9fu, 0x03201005u,
	0x0324d2b1u, 0x032a8382u, 0x03367a04u, 0x03489f2au,
	0x039830d8u, 0x03b4633cu, 0x03e396e0u, 0x03e8eb46u,
	0x04025e6au, 0x042a8f67u, 0x043e1aabu, 0x0449e2cau,
	0x04719ea1u, 0x0477846au, 0x04856d82u, 0x04aa7e6cu,
	0x04e0d1f4u, 0x050787f1u, 0x05147fe0u, 0x0519fde7u,
	0x052c3f05u, 0x0531cea5u, 0x0533b07au, 0x05450e93u,
	0x05aa17e5u, 0x05bb8cabu, 0x05eafcf0u, 0x05f6ec44u,
	0x0621e71cu, 0x062932d2u, 0x06792a33u, 0x06d39a3eu,
	0x06f111e5u, 0x0709c056u, 0x072a5a4au, 0x075af2acu,
	0x0790c057u, 0x07b15fafu, 0x07b200e6u, 0x07c7644eu,
	0x07d2178au);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_7af46712) >= 40u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
	if (kof_find_str_all(scan_range_all, s0, s1))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
