/*
 * Generated by KOFViewer.
 *
 * Researcher:  dmknght
 * Created 2026-09-22
 * Engine:      db format 8, module ABI 2
 */

/*
 * RST, build B - the one that shifts its strings by a character.
 *
 * Filed as a rootkit by some engines, and the hosts say why: ps, netstat,
 * sshd, syslogd, inetd, ifconfig, top. Infecting the tools an administrator
 * looks with IS hiding, whatever the mechanism is called. The mechanism here
 * is infection - payload appended, entry redirected - so the type stays
 * VIRUS and the behaviour is said here instead of being folded into it.
 *
 * ONE RULE PER BUILD; rst_00.c is the other. ONE BLOCK COULD NOT COVER BOTH,
 * and this was measured payload against payload rather than object against
 * object, which is the comparison that matters and is not the same one:
 *
 *     bytes agreeing in place, first 6036    21.9%
 *     16-gram containment                    11.0% and 8.3%
 *     longest identical run                  128 bytes
 *
 * One shared routine of 128 bytes is real and is too short to hash into a
 * block that means anything. So: two payloads, two blocks.
 *
 *
 * WHAT IT ENCODES, AND WHY THAT IS NOT WHAT THE RULE MATCHES.
 *
 * Three strings are moved up one character, and nothing else in the file is:
 *
 *     HFU!0dhj.cjo0ufl!IUUQ02/1   ->  GET /cgi-bin/tek HTTP/1.0
 *     Iptu;!ufl3/qpsu6/dpn        ->  Host: tek2.port5.com
 *     0qspd0vqujnf                ->  /proc/uptime
 *
 * Both halves of that request are on the AUTHOR'S server, so both are theirs
 * to change; the encoding makes them look stronger than they are rather than
 * actually stronger. The block is the detection. The two strings kept below
 * are the second way in, and the plain one of them - /proc with seventeen
 * slashes, which the kernel accepts and a path-matching watcher does not - is
 * a technique rather than a value, which is why it and not the drop name.
 *
 * MEASURED: block score min 50, median 80 across the samples that fire; 0 of
 * 13159 clean objects in /usr/bin and /usr/lib.
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_VIRUS, "RST");

KOF_TARGET_ARCH(KOF_ARCH_X86);

KOF_TARGET_RANGE(scan_range_all, KOF_SCAN_ELF_CODE | KOF_SCAN_ELF_DATA |
				 KOF_SCAN_ELF_NOLOAD | KOF_SCAN_ELF_UNCLAIMED);

KOF_DEFINE_STR(s0, "HFU!0dhj.cjo0ufl!IUUQ02/1", KOF_CASE_EXACT,
	       KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "/proc/////////////////exe", KOF_CASE_EXACT,
	       KOF_WORD_FULLWORD);

KOF_PLAGUE_BLOCK(blk_7aa20c09, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x000812c4u, 0x00092356u, 0x000cb9efu, 0x00136f2fu,
	0x002ea508u, 0x0044dce7u, 0x005bf5f4u, 0x0063db35u,
	0x00915c0cu, 0x00a041e4u, 0x00a7ac16u, 0x00a88e4bu,
	0x01221dc2u, 0x013a13dcu, 0x013b4d01u, 0x01576f9fu,
	0x015ca43bu, 0x0187c155u, 0x01a5cac1u, 0x01c26739u,
	0x01ec9883u, 0x01fd2975u, 0x022ba591u, 0x0230822bu,
	0x0232244du, 0x0280d877u, 0x028476e4u, 0x0285a54fu,
	0x02a84249u, 0x02b59bf0u, 0x02cfacb9u, 0x02e16678u,
	0x02f5f560u, 0x02f755e7u, 0x02fe042eu, 0x0334b0e2u,
	0x035e916au, 0x0366c714u, 0x03811649u, 0x039def57u,
	0x03b8a39cu, 0x03dc96cau, 0x0405976eu, 0x04091096u,
	0x044158f3u, 0x0457ba2du, 0x045f3fc5u, 0x04739b13u,
	0x0473dcfeu, 0x04bb5230u, 0x04d1755cu, 0x04d33adfu,
	0x04dcc43du, 0x04e26300u, 0x05145e7fu, 0x051a5720u,
	0x05594f96u, 0x056f3ff3u, 0x057e888au, 0x0594cf20u,
	0x05a5cd4eu, 0x05a74de2u, 0x05db3ea1u, 0x05ee4b67u,
	0x05fa5cdbu, 0x060e25efu, 0x0614001cu, 0x0614375au,
	0x061e2be3u, 0x0626fe3eu, 0x06460b0au, 0x066cc5e1u,
	0x06a4ffe6u, 0x06ad943fu, 0x06ae5099u, 0x06ae6debu,
	0x06c8593eu, 0x07366d52u, 0x073c5995u, 0x073f3549u,
	0x0769efdau, 0x076b3e7eu, 0x077e21b6u, 0x078e03f0u,
	0x07a0573du, 0x07c8c79bu, 0x07d85791u, 0x07f29960u);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_7aa20c09) >= 40u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
	if (kof_find_str_all(scan_range_all, s0, s1))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
