/*
 * Generated by KOFViewer.
 *
 * Researcher:  dmknght
 * Created 2026-09-22
 * Engine:      db format 8, module ABI 2
 */

/*
 * TWO PAGES BORN WRITABLE AND EXECUTABLE, ONE AFTER THE OTHER.
 *
 * Not a family and not a byte pattern: a shape read out of the code by the
 * sweep in analyzer/disasm/flow.c. What it says is that this program asks the system
 * twice, close together, for memory it can write to and run at the same time.
 *
 * WHY THE W^X BIT IS THE WHOLE RULE. Every serious runtime that generates code
 * - libffi, ld.so, CPython, libswscale - allocates READ|WRITE, emits into it,
 * and only then flips it to READ|EXEC. The page is never both at once. A
 * loader asks for both in one call and keeps them. Measured over 5987 clean
 * objects, every allocation that was executable AND writable at once belonged
 * to a JIT that asks exactly once; not one asked twice in a row.
 *
 * IT RUNS AT HEURISTIC LEVEL 2 AND NOT BELOW. kof_ovl_chain is a full
 * disassembly sweep of the object's code, which is the kind of cost the level
 * gate exists to keep off a caller who did not ask for it - so below level 2
 * the measure answers zero and this rule cannot fire. Block similarity is
 * gated the same way one level down. See c_ovl_chain.
 *
 * MEASURED with the engine, at level 2:
 *
 *     /usr/bin         946 files,  1073 objects     0 fire
 *     /usr/lib       11315 files, 12086 objects     0 fire
 *     VirusSign PE    3024 files,  6306 objects    48 fire
 *
 * So the false positive rate is under 3/12259 by the rule of three, and the
 * recall is 1.6% of that malware set - a narrow rule, deliberately. It is also
 * x86 only IN THE SAMPLES, which is why the target says so rather than
 * claiming the shape is: nothing here was measured on a 64-bit variant.
 *
 * SUSPECT AND NOT INFECT. The shape says how the memory was asked for, not
 * what was put in it, and an obfuscator or a packer nobody has met could
 * reach it honestly.
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofoverlord.h>

KOF_TARGET_FORMAT(KOF_FMT_PE);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "SCLoader");

KOF_TARGET_ARCH(KOF_ARCH_X86);

/* What the samples ask the system for, in order. Read out of their code by
 * the sweep - no bytes of them are kept. The flag is KOF_FLOWF_WX. */
static const struct kof_ovlf_chain ref_chain = {
	.s = {
		{  2u, 0x10u, 0u },   /* alloc-exec, writable at the same time */
		{  2u, 0x10u, 0u },   /* and again, within four nodes */
	},
	.n = 2u
};

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_ovl_chain(ref_chain) >= 100u)
		KOF_SCAN_SUSPECT(KOF_MALVAR_AUTO);
}
