#!/usr/bin/env bash
#
# gen_population.sh - generate a synthetic population of signature modules.
#
#   ./tests/gen_population.sh <count> [outdir]
#
# Why this exists: a prefilter measured against four modules measures nothing. The
# questions that matter - how much memory a database costs, how much of it a scan
# can skip, how scan time grows with the number of records - only have answers at
# a scale nobody is going to hand-write. Until there is a real signature set, a
# synthetic one is the only way to get a number instead of an argument.
#
# What this is NOT: evidence about detection. These modules detect nothing. Every
# pattern here is a random string that will not be found, which is deliberate -
# the interesting case for a scanner is the overwhelming majority of objects that
# do not match, and a population that matched things would measure the rare path.
#
# The mix is a guess and is stated as one, because the real distribution is a
# property of a signature set that does not exist yet. The proportions below are
# what a hand-written set of ELF signatures might plausibly look like; if the real
# one differs, the conclusions change and this script is where to change them.
#
#   40%  region-scoped string search, code+data     - the common case
#   20%  string search in noload                    - toolchain and symbol traces
#   15%  scalar only, no search at all              - structural detections
#   15%  size-constrained string search             - family with a known shape
#   10%  whole-object search, no format target      - the expensive kind

set -euo pipefail

count=${1:-100}
here=$(cd -- "$(dirname -- "$0")" && pwd)
root=$(cd -- "$here/.." && pwd)
outdir=${2:-$root/build/pop}

if ! [ "$count" -gt 0 ] 2>/dev/null; then
	echo "usage: $0 <count> [outdir]" >&2
	exit 2
fi

srcdir=$outdir/src
mkdir -p "$srcdir"
rm -f "$srcdir"/gen_*.c

# Deterministic pseudo-random text, so a run is reproducible and two measurements
# are comparable. Not security relevant; it only has to vary.
rnd() { printf '%s' "$(( (($1 * 1103515245 + 12345) / 65536) % 32768 ))"; }

for i in $(seq 1 "$count"); do
	n=$(printf 'gen_%05d' "$i")
	f=$srcdir/$n.c
	bucket=$(( i % 20 ))
	tag=$(rnd "$i")

	{
		echo "/* generated by gen_population.sh - synthetic, detects nothing */"
		echo "#include <kofmod/kofsig.h>"

		if [ "$bucket" -ge 18 ]; then
			# Whole-object search, applies to any format. The expensive shape.
			echo "KOF_TARGET(KOF_FMT_ANY);"
			echo "KOF_DEFINE_RANGE(all, KOF_SCAN_ALL);"
			echo "KOF_DEFINE_STR(m, \"zqx-$tag-any-marker\", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);"
			echo "KOF_DEFINE_SCAN"
			echo "{"
			echo "	if (kof_find_str(all, m))"
			echo "		KOF_MATCH(\"Synth.Any$i\", KOF_LVL_INFECT);"
			echo "}"
		elif [ "$bucket" -ge 15 ]; then
			# Size-constrained: the precondition the host can act on.
			echo "#include <kofmod/elf.h>"
			echo "KOF_TARGET(KOF_FMT_ELF);"
			echo "KOF_FILESIZE_MIN($(( (i % 7) * 4096 + 512 )));"
			echo "KOF_REQUIRE_ARCH(KOF_ARCH_X86_64);"
			echo "KOF_DEFINE_RANGE(d, KOF_SCAN_ELF_DATA);"
			echo "KOF_DEFINE_STR(m, \"zqx-$tag-sized\", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);"
			echo "KOF_DEFINE_SCAN"
			echo "{"
			echo "	if (kof_find_str(d, m))"
			echo "		KOF_MATCH(\"Synth.Sized$i\", KOF_LVL_INFECT);"
			echo "}"
		elif [ "$bucket" -ge 12 ]; then
			# Scalar only: no search, so nothing to skip it by region.
			echo "#include <kofmod/elf.h>"
			echo "KOF_TARGET(KOF_FMT_ELF);"
			echo "KOF_DEFINE_SCAN"
			echo "{"
			echo "	const struct kof_elf_info *e = kof_elf(ctx);"
			echo "	if (e->e_machine == $(( i % 200 )) && e->seg_count == $(( i % 9 )))"
			echo "		KOF_MATCH(\"Synth.Struct$i\", KOF_LVL_SUSPECT);"
			echo "}"
		elif [ "$bucket" -ge 8 ]; then
			# Sections that are never loaded: absent on stripped objects, which is
			# where the region precondition earns anything.
			echo "#include <kofmod/elf.h>"
			echo "KOF_TARGET(KOF_FMT_ELF);"
			echo "KOF_DEFINE_RANGE(nl, KOF_SCAN_ELF_NOLOAD);"
			echo "KOF_DEFINE_STR(m, \"zqx-$tag-noload\", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);"
			echo "KOF_DEFINE_SCAN"
			echo "{"
			echo "	if (kof_find_str(nl, m))"
			echo "		KOF_MATCH(\"Synth.NoLoad$i\", KOF_LVL_INFECT);"
			echo "}"
		else
			# The common case: two searches over loaded content.
			echo "#include <kofmod/elf.h>"
			echo "KOF_TARGET(KOF_FMT_ELF);"
			echo "KOF_DEFINE_RANGE(loaded, KOF_SCAN_ELF_CODE | KOF_SCAN_ELF_DATA);"
			echo "KOF_DEFINE_RANGE(d, KOF_SCAN_ELF_DATA);"
			echo "KOF_DEFINE_STR(a, \"zqx-$tag-a\", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);"
			echo "KOF_DEFINE_STR(b, \"zqx-$tag-b\", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);"
			echo "KOF_DEFINE_SCAN"
			echo "{"
			echo "	if (kof_find_str(loaded, a)) {"
			echo "		if (kof_find_str(d, b))"
			echo "			KOF_MATCH(\"Synth.Pair$i\", KOF_LVL_INFECT);"
			echo "	}"
			echo "}"
		fi
	} > "$f"
done

echo "generated $count sources in $srcdir"

# Build them. Sequential because ksigcompiler.sh is a pipeline of small processes and the
# point here is the artifacts, not build throughput; xargs -P is used anyway since
# there is no reason to wait.
# Into this population's own artefact directory, never the shared one. ksigbuilder
# packs a directory rather than a list, so building four thousand synthetic modules
# into the same place the real signatures use would put every one of them in the
# next release database - and nothing about that build would look wrong.
artefacts=$outdir/sig
db=${DB:-$outdir/db}
rm -rf "$artefacts" "$db"
mkdir -p "$artefacts" "$db"

jobs=${JOBS:-$(nproc 2>/dev/null || echo 4)}
echo "building with $jobs parallel jobs..."
ls "$srcdir"/gen_*.c | KOF_OUTDIR=$artefacts \
	xargs -P "$jobs" -n 1 "$root/ksigbuilder/ksigcompiler.sh" >/dev/null

built=$(ls "$artefacts"/gen_*.blob 2>/dev/null | wc -l)
echo "built $built blob(s)"
echo "total blob bytes: $(cat "$artefacts"/gen_*.blob 2>/dev/null | wc -c)"

# Pack them, because a population that is not a database cannot be loaded and the
# whole point of generating one is to measure what loading and scanning it costs.
"$root/build/ksigbuilder" "$artefacts" "$db"
echo "load it with: $root/build/kofscanner --db $db --scan-files <path>"
