/*
 * Generated by KOFViewer.
 *
 * Test sample: Exploit.Python.Agent.ak-46d533fad59ef99cfc3b821a67bd41eaed562b4c4342c8f5feaa2455abf55399
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_SCRIPT);
KOF_TARGET_NAME(KOF_MALTYPE_EXPLOIT, "AkitaOnRails");

KOF_TARGET_SUBTYPE(KOF_SCRIPT_PYTHON);

KOF_TARGET_RANGE(scan_range_whole_file, KOF_SCAN_ALL);

KOF_DEFINE_STR(s0, "Coldcard Mk3 Exploit", KOF_CASE_EXACT, KOF_WORD_TOKEN);
KOF_DEFINE_STR(s1, "AkitaOnRails exploit", KOF_CASE_EXACT, KOF_WORD_TOKEN);
KOF_DEFINE_STR(s2, "root.derive(f\"m/84'/0'/0'/{change}/{idx}\")\n", KOF_CASE_EXACT, KOF_WORD_TOKEN);
KOF_DEFINE_STR(s3, "AddressIndex(i).PublicKey().ToAddress()", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s4, "Bip84Coins.BITCOIN", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	/* matcher 1: Threat Actor's credit */
	/* matcher 2: Parts of exploit */
	if (kof_find_str_any(scan_range_whole_file, s0, s1) || kof_find_str_all(scan_range_whole_file, s2, s3, s4))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
