/*
 * Generated by KOFViewer.
 *
 * Test sample: 0b1c49ec2d53c4af21a51a34d9aa91e76195ceb442480468685418ba8ece1ba6_detected_detected
 * Researcher:  dmknght
 * Created 2026-08-28, updated 2026-08-28
 * Engine:      db format 4, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_MINER, "BitcoinMnr");

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_STR(s0, "BitcoinGUI", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "ConnecticoinMiner", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s2, "bitcoinAtStartup", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s3, "getmininginfo", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s4, "src/rpcmining.cpp", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	uint8_t m1 = kof_find_str_multi(scan_range_code, s0, s1, s2, s3, s4);

	if (m1 >= 3)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
	else if (m1 >= 1)
		KOF_SCAN_SUSPECT(KOF_MALVAR_AUTO);
}
