/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.gen-bfb4fc546e7c80572a85cea5828f27621dcefb05a35c06685e43cc67f8d3a48b
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x14000, 3629 bytes, 68 hash(es) */
KOF_PLAGUE_BLOCK(blk_0c3607f1, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x000a58b5u, 0x000a9a94u, 0x004ede80u, 0x005d0cffu,
	0x006a0907u, 0x006ffbd5u, 0x007a8d30u, 0x0084b714u,
	0x00bd0227u, 0x00c07d7au, 0x00c5d4bfu, 0x00e3e83eu,
	0x0112f21bu, 0x0152b725u, 0x015c6b03u, 0x0172e08eu,
	0x017c101eu, 0x01922ca2u, 0x01a8e725u, 0x01c8d1ecu,
	0x01dcd60fu, 0x02291bc1u, 0x029a5c8du, 0x02b2ef18u,
	0x02f6208eu, 0x031364f6u, 0x0342ad34u, 0x035c34f9u,
	0x03815fffu, 0x03af56ffu, 0x03afa1a5u, 0x03d597cdu,
	0x03d7eb7au, 0x03f4cd56u, 0x03fd6a1bu, 0x0418c303u,
	0x04198564u, 0x0423d258u, 0x047b229fu, 0x049eb1a7u,
	0x049f5faau, 0x04a9d44au, 0x04b5ef44u, 0x04cb9b7bu,
	0x04e866a3u, 0x0535792du, 0x05487e31u, 0x0593b5e7u,
	0x0598be19u, 0x05d46569u, 0x05fd14f4u, 0x0617ea11u,
	0x061831a1u, 0x062ba0bbu, 0x06346172u, 0x0636f420u,
	0x064487b5u, 0x065f6ae6u, 0x067a8b21u, 0x070c7073u,
	0x070e0699u, 0x07131227u, 0x07640b28u, 0x076860b5u,
	0x07cf94cfu, 0x07d510c1u, 0x07e9c5e8u, 0x07fda80du);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_0c3607f1) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
