/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.dx-e0b4452d124b20af7860b9e27fadc279c331a1641db652ad9dff5237a0c53f6b
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x1a000, 1458 bytes, 30 hash(es) */
KOF_PLAGUE_BLOCK(blk_6d9296cd, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x00480b67u, 0x006796fbu, 0x0133da5au, 0x013f24ecu,
	0x0142c5bcu, 0x016f6eccu, 0x0196b3c4u, 0x01ccad6du,
	0x01d390a6u, 0x024e63f4u, 0x0250146du, 0x03090f92u,
	0x03a9948cu, 0x03b0f0c4u, 0x03c52802u, 0x03e01767u,
	0x045ac763u, 0x0489ee2au, 0x04b9d81au, 0x051c274du,
	0x056d09f1u, 0x06286815u, 0x0648aea7u, 0x0680bd38u,
	0x06d7c69bu, 0x06d891feu, 0x076880c3u, 0x079c7702u,
	0x07b74153u, 0x07f3aa04u);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_6d9296cd) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
