/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.cw-020befb269ba8f931ff2cb5056c769b65d7b6b6cae0fa5468c00fa51b9429f81
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x15000, 2724 bytes, 65 hash(es) */
KOF_PLAGUE_BLOCK(blk_cd9fa34d, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x001b6e1bu, 0x00701a78u, 0x00b6e125u, 0x00c8f8a1u,
	0x00d6cddau, 0x00f8ee66u, 0x00fc89bbu, 0x01064910u,
	0x014a5f6eu, 0x014d3ab7u, 0x017fa33cu, 0x01ad105eu,
	0x01fa6783u, 0x02096240u, 0x022ec9dau, 0x027f283eu,
	0x028684bfu, 0x02b87735u, 0x02e11aedu, 0x02e65c63u,
	0x030a865au, 0x030a87d8u, 0x032c11a8u, 0x0357d830u,
	0x03c507dau, 0x03cabfecu, 0x03ce4386u, 0x03dda16du,
	0x03e41075u, 0x04558dd1u, 0x04607b63u, 0x0479338au,
	0x047afe79u, 0x049efe43u, 0x04c36e80u, 0x04e402feu,
	0x0529773du, 0x05468159u, 0x0552e7bau, 0x057e5c10u,
	0x0580b7eau, 0x05843601u, 0x058e34d9u, 0x059a2928u,
	0x05a82b31u, 0x05ae7c98u, 0x05c03111u, 0x05dae4fdu,
	0x05eb7c36u, 0x060d922eu, 0x0661321fu, 0x06ae0db7u,
	0x06ed01e5u, 0x06fca09cu, 0x07242106u, 0x073632deu,
	0x0751c42au, 0x077882d9u, 0x07a559b2u, 0x07b9d270u,
	0x07da7c03u, 0x07e7fc79u, 0x07ef7732u, 0x07f3b604u,
	0x07fbbcf2u);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_cd9fa34d) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
