/*
 * Generated by KOFViewer.
 *
 * Test sample: normalized:HEUR-Backdoor.Linux.Mirai.b-036f5b0ccd595315d4c10fca45bca7fcbb786d93b01c42d5b979bc5d45c02d46
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 4
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "VapeBot");

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_STR(s0, "VapeBot/Locker", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "VapeBot has been executed", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
/* +0xd245, 6871 bytes, 128 hash(es) */
KOF_PLAGUE_BLOCK(blk_8cbbff58, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x000a58b5u, 0x000a9a94u, 0x00112045u, 0x001dcbe6u,
	0x002ce838u, 0x003279c0u, 0x003b9c14u, 0x00452bf7u,
	0x0047683eu, 0x004f29c4u, 0x00503459u, 0x0052cddbu,
	0x005f9a49u, 0x006200feu, 0x00628a5fu, 0x006b06bau,
	0x006f3d74u, 0x0073fe3bu, 0x007b6d4au, 0x007cee34u,
	0x0085b5abu, 0x00ae9acbu, 0x00afb32fu, 0x00b0982au,
	0x00b3115cu, 0x00c07d7au, 0x00c5d4bfu, 0x00c6a10eu,
	0x00c74e29u, 0x00cfc4a4u, 0x00d5153bu, 0x00e01b86u,
	0x00ebe218u, 0x00ebfa54u, 0x00ec3829u, 0x00ef5c0eu,
	0x00f8f932u, 0x0101c686u, 0x010ca36du, 0x0115455bu,
	0x012239e2u, 0x0123b7ebu, 0x0123e662u, 0x012a8056u,
	0x013202b5u, 0x0132c0f5u, 0x013a5fb2u, 0x013dc281u,
	0x013f24ecu, 0x013f33e0u, 0x01488073u, 0x0152b725u,
	0x01573fbdu, 0x016ca6a0u, 0x017aab9cu, 0x017d4a98u,
	0x017ec5edu, 0x0180a047u, 0x01816246u, 0x01866dc5u,
	0x018699f4u, 0x01961b33u, 0x019e463cu, 0x01a0cdcau,
	0x01b50125u, 0x01bfa3f5u, 0x01c6c21du, 0x01c8ebeau,
	0x01ccad6du, 0x01d390a6u, 0x01d5f1ceu, 0x01d7ab9du,
	0x01dcd60fu, 0x01dda835u, 0x01ea4290u, 0x02000ee7u,
	0x020d255cu, 0x02119e3eu, 0x02131f6cu, 0x0216d0d9u,
	0x02175c06u, 0x02291bc1u, 0x022bb713u, 0x022e2d62u,
	0x02330986u, 0x023cec45u, 0x0243fc52u, 0x024bb0edu,
	0x024bcc38u, 0x025d1801u, 0x025d6245u, 0x025ef03eu,
	0x026af5ebu, 0x026eefc1u, 0x02793f22u, 0x0286b9f4u,
	0x0287759cu, 0x028b38b7u, 0x0294170au, 0x02ad9655u,
	0x02ad978au, 0x02b2ef18u, 0x02c81152u, 0x02c85a00u,
	0x02d62affu, 0x02eb7ff0u, 0x03067851u, 0x0309f53bu,
	0x030f8e02u, 0x030fb79eu, 0x03136523u, 0x0314d91bu,
	0x0316346au, 0x03273ab1u, 0x0329fc36u, 0x03300a58u,
	0x03319786u, 0x0331b32eu, 0x03375945u, 0x033a8a6cu,
	0x0342ad34u, 0x0343ccb4u, 0x0347404au, 0x034c6eb4u,
	0x034cd437u, 0x034fd565u, 0x0350712bu, 0x0353abb3u);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_code, s0, s1) || kof_plague_score(blk_8cbbff58) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
