/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.n-0781d164ad718340e5a359c13527d75f55c8d01150f514cb0a7c05cff35f766a
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0xf000, 4160 bytes, 87 hash(es) */
KOF_PLAGUE_BLOCK(blk_54b4a799, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x0010d5f1u, 0x00642ff4u, 0x007d0021u, 0x0085d4ccu,
	0x009c0a15u, 0x00d2963du, 0x00f88806u, 0x01074951u,
	0x010d2256u, 0x015fd261u, 0x0170a064u, 0x018e6d22u,
	0x01915a59u, 0x01931b5cu, 0x019e3202u, 0x01b95c72u,
	0x01ccd3ddu, 0x01e7e8b1u, 0x0221bb15u, 0x022ac6d5u,
	0x023b79fdu, 0x02493fe2u, 0x0255adfcu, 0x0259caf2u,
	0x02608dadu, 0x0269fbfbu, 0x02823687u, 0x02885217u,
	0x028cdd07u, 0x029408ddu, 0x029ac7c0u, 0x029e63bdu,
	0x02a7be24u, 0x02ab8ea7u, 0x02d7381du, 0x02dfb884u,
	0x02e3cf81u, 0x0315cfddu, 0x0340b7b3u, 0x0363ba61u,
	0x03645049u, 0x03787492u, 0x038c0d20u, 0x039d35b4u,
	0x03a00df6u, 0x03b49c71u, 0x03bacc9cu, 0x03bb78a6u,
	0x03bed499u, 0x03d3ef9eu, 0x03da88d3u, 0x0407593bu,
	0x041a6db7u, 0x0486ed06u, 0x052aadfeu, 0x057137cbu,
	0x05a8ccc3u, 0x05ae5841u, 0x05be0953u, 0x05db0093u,
	0x0613d9acu, 0x06193ef3u, 0x06201139u, 0x0623ff8au,
	0x062ad65eu, 0x063b489fu, 0x064cb60du, 0x0666fc54u,
	0x0669f3a7u, 0x067642afu, 0x0693eba9u, 0x06b2aa63u,
	0x06f4260cu, 0x0747de75u, 0x0753daf3u, 0x075516c6u,
	0x0766db72u, 0x076f0d13u, 0x0782ff52u, 0x07a83894u,
	0x07b1380bu, 0x07b56074u, 0x07b9b606u, 0x07c18dccu,
	0x07dadab6u, 0x07dd07d7u, 0x07fca482u);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_54b4a799) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
