/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.b-34a7a0c034006b793876421ee00f70a5318a65b15837f11e77d4f7d5e7b33ac5
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x27000, 4160 bytes, 67 hash(es) */
KOF_PLAGUE_BLOCK(blk_bde6ba1f, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x00364bb7u, 0x005e2d34u, 0x006200feu, 0x00b0982au,
	0x00b6a21eu, 0x00d42502u, 0x00e70ec3u, 0x013f24ecu,
	0x013f33e0u, 0x019f9457u, 0x01b1512bu, 0x01c9c861u,
	0x01ccad6du, 0x01d929bcu, 0x01ed9d61u, 0x021efd8au,
	0x0260759fu, 0x02793f22u, 0x029255aeu, 0x02ae95e9u,
	0x02c58279u, 0x02d440cdu, 0x02e8ec0au, 0x02ee8fdcu,
	0x031f4c87u, 0x033471a2u, 0x0384206au, 0x03b65e44u,
	0x03c52802u, 0x03db3bbfu, 0x03dbc7c8u, 0x03e01767u,
	0x03f2bbd1u, 0x0437e1c5u, 0x043af16bu, 0x0450d4b3u,
	0x048ead4au, 0x048ebab8u, 0x049d2defu, 0x04a1ac33u,
	0x04b24227u, 0x04bccb31u, 0x04d74a5du, 0x04ea90aau,
	0x0501f29au, 0x052e5032u, 0x055e36e9u, 0x05c8c72du,
	0x05c8cdd7u, 0x05fa065bu, 0x064d19a9u, 0x06527853u,
	0x0680bd38u, 0x06b4a202u, 0x06c82812u, 0x06ca6023u,
	0x06f6900du, 0x0710414fu, 0x0736fb77u, 0x0760c182u,
	0x07a14cddu, 0x07b03fd8u, 0x07c113cbu, 0x07c7c3e3u,
	0x07cfdef1u, 0x07cff25cu, 0x07dc30e2u);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_bde6ba1f) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
