/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.h-cc7bcbeed4c561774c6f2a8f38fcdbe465ac8a6c3670001d8286dd290ed0ece0
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x4000, 4160 bytes, 85 hash(es) */
KOF_PLAGUE_BLOCK(blk_588d7a8c, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x000c4a58u, 0x00495b5eu, 0x0056edf1u, 0x00634889u,
	0x008c5862u, 0x00bef5dfu, 0x00de5b8fu, 0x00e28b66u,
	0x00f1348au, 0x011ef4d3u, 0x0136bdc4u, 0x0141bda0u,
	0x0147a5fcu, 0x018f6944u, 0x019c0747u, 0x01aa4704u,
	0x01b25f98u, 0x01b7ac84u, 0x01c49ccdu, 0x01c5170du,
	0x01f15d6au, 0x0260ca14u, 0x027cb2acu, 0x02853e9fu,
	0x02b0ba4bu, 0x02ee4f5du, 0x03154492u, 0x031c55b9u,
	0x03426f69u, 0x036fd050u, 0x03712f8au, 0x037789adu,
	0x0386fa12u, 0x03a64d18u, 0x03cc1c7fu, 0x03e142c8u,
	0x03f2e781u, 0x040d3a0au, 0x040e840fu, 0x041a2c27u,
	0x04285c48u, 0x043c2d24u, 0x044db4e6u, 0x0471ae2cu,
	0x0474073bu, 0x0478df7bu, 0x04cd38feu, 0x04d1a9d2u,
	0x04d25515u, 0x04df9c9du, 0x04e22448u, 0x04fedb15u,
	0x054170a0u, 0x05467a4du, 0x05578b24u, 0x05769bcfu,
	0x05a64279u, 0x05b28179u, 0x05bca13eu, 0x05e4b747u,
	0x05e56ecdu, 0x063e5df3u, 0x063f4c8eu, 0x06698dd2u,
	0x0680902eu, 0x06903bc9u, 0x069d2decu, 0x06cc9e38u,
	0x06daf38eu, 0x06de5560u, 0x06dee764u, 0x072a6d52u,
	0x073d0c70u, 0x073e7398u, 0x0740a7b7u, 0x074f7763u,
	0x075a1c76u, 0x0762eaa5u, 0x07957367u, 0x079805ebu,
	0x07aeed5fu, 0x07ea5490u, 0x07f30215u, 0x07f749a4u,
	0x07f8d11cu);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_588d7a8c) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
