/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.hv-91fa1ef98caaf8740e666935ffdcfbe93085a6a02398b5fecb188a02031b393c
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x16000, 1905 bytes, 58 hash(es) */
KOF_PLAGUE_BLOCK(blk_fc8f9240, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x005dee05u, 0x006ed8dbu, 0x007b90acu, 0x007ea160u,
	0x00c07d70u, 0x0146463cu, 0x018ae14au, 0x01a3b92eu,
	0x01b51900u, 0x021412e6u, 0x025e0cbbu, 0x026f5f1au,
	0x0285e853u, 0x02ab5199u, 0x02c77a44u, 0x02e7fb7fu,
	0x02ef80deu, 0x0303dfefu, 0x03260e5cu, 0x03376551u,
	0x033fa6bfu, 0x0385bb88u, 0x03864bcau, 0x03888202u,
	0x039092b8u, 0x0396cb41u, 0x03a32948u, 0x03f195a7u,
	0x03ff8e86u, 0x0407c184u, 0x0436d404u, 0x04473b3bu,
	0x0472199eu, 0x0486ecdfu, 0x04887a40u, 0x04b5e65du,
	0x04d1925au, 0x05030ff5u, 0x0507eabbu, 0x05256323u,
	0x053ce875u, 0x058cdd35u, 0x0593914fu, 0x0599d863u,
	0x05df65b1u, 0x065aa47cu, 0x065f6ee1u, 0x06649614u,
	0x06920189u, 0x069be35cu, 0x06b7585eu, 0x06d32df5u,
	0x06d3ea76u, 0x06fbbfdeu, 0x0767ba53u, 0x078bac0cu,
	0x07ea2aa5u, 0x07f64d6fu);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_fc8f9240) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
