/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.mp-857101911534f6ca623a9d5d90588f1138d0919a42e89a6ca685e0cc8c7bd692
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0xe000, 3362 bytes, 72 hash(es) */
KOF_PLAGUE_BLOCK(blk_09d9a14c, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x0015fe98u, 0x002e40ecu, 0x0056306cu, 0x0067db73u,
	0x008ec4d0u, 0x00b46f1cu, 0x00bb7713u, 0x00c9ea8du,
	0x00f94e0fu, 0x00fb2622u, 0x00fd34f6u, 0x0125a43du,
	0x01742485u, 0x01860acfu, 0x01898653u, 0x018ff4c8u,
	0x01f3df13u, 0x01f5f4a2u, 0x02488968u, 0x02911a0bu,
	0x02963ed5u, 0x02b2ef18u, 0x02c58032u, 0x030e1d23u,
	0x030e8275u, 0x031a956bu, 0x031ebb0au, 0x0334317du,
	0x0342ad34u, 0x03ae5105u, 0x03bf9866u, 0x03d27e2cu,
	0x0414020eu, 0x041e066cu, 0x044b9938u, 0x0459a02au,
	0x04616d03u, 0x047b229fu, 0x049d7ff0u, 0x04a9c090u,
	0x04b358c8u, 0x04c45276u, 0x04d030d3u, 0x04f94e31u,
	0x04fe154fu, 0x0536c02cu, 0x05487e31u, 0x05512d0bu,
	0x0558a43bu, 0x05688775u, 0x05786e0au, 0x057bef2bu,
	0x05972a9cu, 0x059fa3d2u, 0x05b2cb12u, 0x05d3e7a9u,
	0x06196427u, 0x064487b5u, 0x0644a481u, 0x06a243a5u,
	0x06c345ecu, 0x06d8063eu, 0x06f9406fu, 0x0701acb3u,
	0x072b3aaeu, 0x07399140u, 0x073e43e3u, 0x076cc12cu,
	0x07798fa2u, 0x078cbd5cu, 0x07bdcf99u, 0x07ea5580u);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_09d9a14c) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
