/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.cw-15d44f49786a0e06bb026e05ee4c6f6245fc24d9b002e2f6ca4f847693fcf321
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0xe000, 4160 bytes, 38 hash(es) */
KOF_PLAGUE_BLOCK(blk_458f3453, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x00dcec1du, 0x01309fa3u, 0x013f24ecu, 0x013f33e0u,
	0x01603359u, 0x018b1c13u, 0x018f0849u, 0x01ccad6du,
	0x02095eefu, 0x021efd8au, 0x023601e8u, 0x02793f22u,
	0x02ee8fdcu, 0x03463838u, 0x038f1a7au, 0x038f6101u,
	0x0397056au, 0x03c52802u, 0x03d7eb7au, 0x03db3bbfu,
	0x03e01767u, 0x03e52664u, 0x03f2bbd1u, 0x04979b66u,
	0x049f5faau, 0x04bccb31u, 0x04cfeeb3u, 0x0584cc3fu,
	0x05c8cdd7u, 0x05e51755u, 0x05f86584u, 0x064b7b5bu,
	0x0680bd38u, 0x06ae23a7u, 0x071018b5u, 0x073a387bu,
	0x075188f7u, 0x07b03fd8u);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_458f3453) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
