/*
 * Generated by KOFViewer.
 *
 * Test sample: normalized:HEUR-Backdoor.Linux.Mirai.b-02ce9b736cd71658c564d56dd15db84a73e81cfe4a22612c183c0c692adf6677
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "DarknessBot");

KOF_TARGET_RANGE(scan_range_data, KOF_SCAN_ELF_DATA);

KOF_DEFINE_STR(s0, "Darkness_Botnet_2026", KOF_CASE_EXACT, KOF_WORD_TOKEN);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_all(scan_range_data, s0))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
