/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.cw-ed82c283b9914061aa394666f9fb12045796bae54ca71e577dc8ac34eb42838f
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x22000, 1784 bytes, 45 hash(es) */
KOF_PLAGUE_BLOCK(blk_d57235c6, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x0039e442u, 0x004f29c4u, 0x0061c524u, 0x006a7eafu,
	0x00e01b86u, 0x0109039bu, 0x01488073u, 0x0152b725u,
	0x017e79a0u, 0x01a4dffdu, 0x01dc5d65u, 0x02291bc1u,
	0x02519b06u, 0x02a9f9bcu, 0x02b2ef18u, 0x0300c025u,
	0x0314d91bu, 0x0316346au, 0x0342ad34u, 0x03985d9cu,
	0x03a7247cu, 0x03af56ffu, 0x03b0be3du, 0x03fd6a1bu,
	0x04049a3fu, 0x040f83d1u, 0x0423d258u, 0x047b229fu,
	0x049eb1a7u, 0x049f5faau, 0x04b5ef44u, 0x04d18ba3u,
	0x04d6f932u, 0x0515e1f6u, 0x0520be22u, 0x05487e31u,
	0x05dc6a40u, 0x066e20c2u, 0x06d69917u, 0x07086334u,
	0x070c7073u, 0x07131227u, 0x0721d4dcu, 0x07cdd989u,
	0x07f2a0c5u);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_d57235c6) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
