/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.mu-8976033d6173502d498324b4b04e0a5140627d3beb61b71da98f0d37b8c13ac1
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x67000, 4160 bytes, 89 hash(es) */
KOF_PLAGUE_BLOCK(blk_82edb290, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x0026bbc8u, 0x002bed90u, 0x002e40ecu, 0x0067db73u,
	0x006b810cu, 0x006bec66u, 0x00893653u, 0x008ec4d0u,
	0x00a0cbc4u, 0x00c309d1u, 0x00fb2622u, 0x00feac85u,
	0x011b66a3u, 0x014748a0u, 0x014d4ba6u, 0x01507240u,
	0x015f83c0u, 0x01742485u, 0x01898653u, 0x019b1f7bu,
	0x01d390a6u, 0x01deafecu, 0x01e56fa0u, 0x02059244u,
	0x02488968u, 0x0287b747u, 0x02911a0bu, 0x02963ed5u,
	0x02b2ef18u, 0x02edcf63u, 0x02f31663u, 0x0307ecb3u,
	0x031a956bu, 0x0337bc22u, 0x0342ad34u, 0x036eced6u,
	0x03941e79u, 0x039578b5u, 0x03ab4ec4u, 0x03b27f96u,
	0x03b8707du, 0x03bf9866u, 0x03d23149u, 0x03fc6daeu,
	0x0414020eu, 0x041e066cu, 0x04252bfbu, 0x04616d03u,
	0x0468c772u, 0x04795285u, 0x047b229fu, 0x047ba517u,
	0x048b7761u, 0x049d7ff0u, 0x04a2371cu, 0x04a9c090u,
	0x04b5be78u, 0x04bddf4au, 0x04c45276u, 0x04e2e271u,
	0x04e3c810u, 0x04fe154fu, 0x0504aaf8u, 0x05272994u,
	0x0536c02cu, 0x0546ece0u, 0x05527489u, 0x05688775u,
	0x0569ddcau, 0x056ca31eu, 0x057b96ceu, 0x057bef2bu,
	0x05cf585eu, 0x05d0fcc9u, 0x05f78e75u, 0x060a16e3u,
	0x06196427u, 0x064b48c8u, 0x06a138a0u, 0x06b88c54u,
	0x06c345ecu, 0x06f9406fu, 0x0722b554u, 0x073e43e3u,
	0x075b39e0u, 0x075fa1e2u, 0x077d5007u, 0x078cbd5cu,
	0x07bb2007u);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_82edb290) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
