/*
 * Generated by KOFViewer.
 *
 * Test sample: 2023eafb964cc555ec9fc4e949db9ba3ec2aea5c237c09db4cb71abba8dcaa97
 */

/*
 * Some called EbolaChan, some called Ladvix on VirusTotal
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Flooder");

KOF_TARGET_RANGE(scan_range_unclaimed, KOF_SCAN_ELF_UNCLAIMED);

KOF_DEFINE_STR(s0, "Server Killer kekW", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "Attack In Progress", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s2, "Attack Started", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s3, "| base64 --decode | bash", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_multi(scan_range_unclaimed, s0, s1, s2) >= 2)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
	else if (kof_find_str_any(scan_range_unclaimed, s3))
		KOF_SCAN_SUSPECT(KOF_MALVAR_AUTO);
}
