/*
 * Generated by KOFViewer.
 *
 * Test sample: 4eadf80e85656f2c30bf8656cd5ea1a46cfb2557388b911b3644e659900513fe.elf
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_STR(s0, "killerEXE", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "killerStat", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s2, "killerMaps", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s3, "boatnet", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s4, "softbot", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s5, "Self Rep Fucking NeTiS and Thisity 0n Ur FuCkInG FoReHeAd We BiG L33T HaxErS", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s6, "TSource Engine Querym", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_code, s0, s1, s2, s3, s4, s5, s6))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
