/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.ms-552fd7f65d88d0bcbab4a158789ee908a9ac57f3f0405544c4ebac3217a51cf4
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x1d000, 4160 bytes, 88 hash(es) */
KOF_PLAGUE_BLOCK(blk_a23378b4, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x00407bccu, 0x004ff178u, 0x006200feu, 0x00621426u,
	0x0072efcdu, 0x007d3ab3u, 0x00893653u, 0x00b0982au,
	0x00b95e29u, 0x00e719c0u, 0x010134aeu, 0x012596ffu,
	0x013f24ecu, 0x013f33e0u, 0x0143a1e6u, 0x01451ff8u,
	0x0151f095u, 0x01715336u, 0x01aacfa3u, 0x01bbf76cu,
	0x01ccad6du, 0x01d1134au, 0x01d390a6u, 0x01d4c3c0u,
	0x01faef77u, 0x021db031u, 0x0222f71fu, 0x024e3232u,
	0x0254e92cu, 0x02793f22u, 0x027bbf41u, 0x027dbd6au,
	0x029ca2f4u, 0x02a5574au, 0x02a866cbu, 0x02d16911u,
	0x02edcf63u, 0x0311c284u, 0x031364f6u, 0x032e7d0bu,
	0x03452b5bu, 0x03aa3298u, 0x03bf9866u, 0x03db3bbfu,
	0x03e01767u, 0x03f2bbd1u, 0x03fa7ea9u, 0x04233db2u,
	0x042d8013u, 0x042e1d79u, 0x043af16bu, 0x04475ae1u,
	0x045eaae8u, 0x047a51e2u, 0x047ba62fu, 0x048e1e57u,
	0x049cf6ffu, 0x049fc819u, 0x04bccb31u, 0x04bcf9abu,
	0x04d24137u, 0x04dbb8a9u, 0x04e00729u, 0x04e3461cu,
	0x04e9fd93u, 0x04f8a1c7u, 0x05105f9bu, 0x05487e31u,
	0x057a48c1u, 0x0597fd5cu, 0x05d17c24u, 0x05e4a3f3u,
	0x061478c3u, 0x0666775du, 0x066a90f6u, 0x067657aeu,
	0x0680bd38u, 0x068d20ebu, 0x06b88c54u, 0x06e33b31u,
	0x06f9406fu, 0x0731506du, 0x0783ffa9u, 0x078cbd5cu,
	0x07987f97u, 0x07b03fd8u, 0x07cf02d8u, 0x07cfdef1u);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_a23378b4) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
