/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.hv-68f80754cd0fb815fd7be93acf76d3a5c0f05d94ffec7ffa936a8ad53965f514
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x1e000, 2570 bytes, 77 hash(es) */
KOF_PLAGUE_BLOCK(blk_29204375, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x00030cfcu, 0x0034380au, 0x003ee7b8u, 0x005e5839u,
	0x007d1f00u, 0x008be0e0u, 0x00dee7f4u, 0x00e276b0u,
	0x012246deu, 0x016a6686u, 0x01752599u, 0x017feca4u,
	0x01994310u, 0x01b649c4u, 0x01b7dce0u, 0x01dd8695u,
	0x01ed60d7u, 0x01f91a88u, 0x01f9fcdau, 0x020244bfu,
	0x02129157u, 0x02523214u, 0x0256370eu, 0x0258ba44u,
	0x027a680bu, 0x028136a7u, 0x02cd9bb5u, 0x02d03469u,
	0x03209c47u, 0x038ad739u, 0x03b9139du, 0x03c90d95u,
	0x03d5fb7au, 0x03e2eebeu, 0x03e9dc11u, 0x03e9df49u,
	0x0423a4f9u, 0x042d3e5eu, 0x046ffc87u, 0x04acc31au,
	0x04b1df22u, 0x04bda11fu, 0x04ea9870u, 0x04ebcf27u,
	0x04ee9c9du, 0x050a0e07u, 0x051258e6u, 0x05151a4du,
	0x0519512au, 0x05346457u, 0x0542607eu, 0x0555f6a9u,
	0x055c861du, 0x056c9865u, 0x05777998u, 0x05993f3eu,
	0x05a220b4u, 0x05a690edu, 0x05a7866bu, 0x05eb97b3u,
	0x0619f992u, 0x061b9646u, 0x068cdb1du, 0x06960e57u,
	0x06cb2c72u, 0x06dbc033u, 0x06fc5eceu, 0x071b33d4u,
	0x07215254u, 0x072c4195u, 0x072d07cau, 0x0748a5c0u,
	0x0775a564u, 0x078d176bu, 0x07a815beu, 0x07c407aau,
	0x07d76cacu);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_29204375) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
