/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.b-64ebf723abb8d3cf07df9d682d5342f93a6e69bc2245cdbb3c7b38003667ce43
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0x2000, 4160 bytes, 84 hash(es) */
KOF_PLAGUE_BLOCK(blk_c4291826, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x0041d8abu, 0x00a11729u, 0x00b2452bu, 0x00b59bcdu,
	0x00d1463eu, 0x00dd25bfu, 0x00fb8df0u, 0x012e85a4u,
	0x01557d69u, 0x0170bf18u, 0x018311e3u, 0x018be772u,
	0x01c7b259u, 0x01e52e04u, 0x01e971c3u, 0x01ed542bu,
	0x0221b3d8u, 0x0240f0fbu, 0x0252ffdfu, 0x027326a7u,
	0x029bcc64u, 0x02aa0eedu, 0x02bcdfbau, 0x02c04a62u,
	0x02d0e96fu, 0x02eaee6eu, 0x02f1057fu, 0x02fb3264u,
	0x02fbb6e4u, 0x0301bd86u, 0x03093793u, 0x030dffdfu,
	0x031365adu, 0x031495eau, 0x034d5d61u, 0x0366e7f2u,
	0x036de2c0u, 0x0374e877u, 0x0379f4b8u, 0x0387ae48u,
	0x03d5e8f5u, 0x041db8aeu, 0x044e6869u, 0x0458cef0u,
	0x0481390eu, 0x04910a78u, 0x04b8d1c7u, 0x04bb5e43u,
	0x04cca5edu, 0x04e54a4eu, 0x05071da4u, 0x053fa523u,
	0x054e3b7du, 0x05617c43u, 0x056b3b47u, 0x056c5c56u,
	0x05b149d1u, 0x0617ec3cu, 0x061aad8cu, 0x062d49e0u,
	0x063bae9du, 0x0650bb5eu, 0x06579653u, 0x066da1eeu,
	0x0679b756u, 0x0689cbc8u, 0x0690daa0u, 0x06926596u,
	0x06bbc9b4u, 0x06bd6194u, 0x06cac062u, 0x06ccbec9u,
	0x06cdbcf1u, 0x07065e71u, 0x070fe4c9u, 0x0712b682u,
	0x0738ba93u, 0x07678193u, 0x0799029bu, 0x079e3338u,
	0x07ab56c6u, 0x07cc2d1au, 0x07eb34d5u, 0x07f5f8e3u);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_c4291826) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
