/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Mirai.r-7b651e4f66c0bcc2befa5a981caaf7ea1180b8bb530bb1e384ba42e70f097db1
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>
#include <kofmod/kofplague.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

/* +0xd000, 4160 bytes, 89 hash(es) */
KOF_PLAGUE_BLOCK(blk_9d8c6f7e, KOF_SCAN_ELF_CODE, KOF_PLAGUE_RAW,
	0x000ec9d7u, 0x0010403au, 0x0018e315u, 0x004e369du,
	0x005d4123u, 0x0071dfacu, 0x00843224u, 0x009ad05au,
	0x00bdbba7u, 0x00dbca32u, 0x00f818d9u, 0x0103f334u,
	0x0106b033u, 0x01125131u, 0x01199abau, 0x0162bd5eu,
	0x016dd129u, 0x018ba593u, 0x01bc13ffu, 0x0203b278u,
	0x0212a841u, 0x0221f5e3u, 0x0287441bu, 0x02a6ec2cu,
	0x02a7648du, 0x02cf2bd7u, 0x02d1a449u, 0x02dd1fa6u,
	0x02e9fc5cu, 0x02ebeb2bu, 0x0305fe06u, 0x030b60eeu,
	0x03248f5au, 0x032c32d0u, 0x0334ac25u, 0x0341863bu,
	0x037f79b3u, 0x039f5d22u, 0x03c36f6bu, 0x03cb3eb6u,
	0x03dddcf4u, 0x03f0f5fbu, 0x03f3c2d1u, 0x03fbd42cu,
	0x042c89ccu, 0x043cde98u, 0x043eb71bu, 0x044475e1u,
	0x04989330u, 0x04993da7u, 0x049ed05au, 0x04a367a7u,
	0x04d55126u, 0x0505d526u, 0x05072566u, 0x0527aed3u,
	0x0529671cu, 0x05720b2bu, 0x058f3d19u, 0x05d1bc5du,
	0x05d98f11u, 0x05fcad36u, 0x061d5549u, 0x06223b17u,
	0x06574410u, 0x06847d8au, 0x06887505u, 0x06907fa9u,
	0x06a465d6u, 0x06cb4f12u, 0x06f28d39u, 0x06f61f7du,
	0x06fa6b6cu, 0x06fe65b8u, 0x0700f2a4u, 0x07057131u,
	0x07387b17u, 0x075a0549u, 0x075cd4dbu, 0x0783290fu,
	0x078b0c44u, 0x07abe317u, 0x07bcb1cdu, 0x07dcf5a0u,
	0x07ddff63u, 0x07eab133u, 0x07ec5869u, 0x07f8d42au,
	0x07fff2bbu);


void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_plague_score(blk_9d8c6f7e) >= 70u)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
