/*
 * Generated by KOFViewer.
 *
 * Test sample: 8f6d00126d11243b5879fa5a05a53236488ac9af856ddd9d7d3882516e346544
 * Researcher:  dmknght
 * Created 2026-08-30, updated 2026-08-30
 * Engine:      db format 6, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "CamFrog");

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_STR(s0, "Syn-Flood", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "land udp attack", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s2, "Camfrog Ra", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_multi(scan_range_code, s0, s1, s2) >= 2)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
