/*
 * Generated by KOFViewer.
 *
 * Test sample: diamorphine.ko
 * Test sample: 5d637915abc98b21f94b0648c552899af67321ab06fb34e33339ae38401734cf
 * Researcher:  dmknght
 * Created 2026-08-30, updated 2026-08-30
 * Engine:      db format 6, module ABI 2
 */

/*
 * Build on kernel before 6.9.0 (6.0.0). Some symbols are missings. It's very easy to bypass. Added a sample built on kernel 3.X
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_ROOTKIT, "Diamorphine");

KOF_TARGET_SUBTYPE(KOF_ELF_REL);

KOF_TARGET_RANGE(scan_range_data_noload, KOF_SCAN_ELF_DATA | KOF_SCAN_ELF_NOLOAD);

KOF_DEFINE_STR(s0, "description=LKM rootkit", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "author=m0nad", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s2, "name=diamorphine", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s3, "diamorphine.c", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s4, "diamorphine.mod.c", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s5, "diamorphine.h", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	/* matcher 1: Default fingerprints of Diamorphine, open-source version. Very easy to bypass. */
	if (kof_find_str_any(scan_range_data_noload, s0, s1, s2, s3, s4, s5))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
