/*
 * Generated by KOFViewer.
 *
 * Test sample: diamondxe.ko
 *
 * Build on kernel >= 6.9.0 (tested on 7.0.7) where x64_sys_call symbol is declared.
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_ROOTKIT, "Diamorphine");

KOF_TARGET_RANGE(scan_range_data, KOF_SCAN_ELF_DATA);

KOF_DEFINE_STR(s0, "sys_call_table", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "x64_sys_call", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s2, "kallsyms_lookup_name", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_all(scan_range_data, s0, s1, s2))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
