/*
 * Generated by KOFViewer.
 *
 * Test sample: diamorphine.ko
 */

/*
 * Build on kernel before 6.9.0 (6.0.0). Some symbols are missings. It's very easy to bypass. Otherwise only symbols might create FP.
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_ROOTKIT, "Diamorphine");

KOF_TARGET_SUBTYPE(KOF_ELF_REL);

KOF_TARGET_RANGE(scan_range_data, KOF_SCAN_ELF_DATA);

KOF_DEFINE_STR(s0, "sys_call_table", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "kallsyms_lookup_name", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s2, "description=LKM rootkit", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s3, "author=m0nad", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s4, "name=diamorphine", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	/* matcher 1: Declared symbols to hook functions */
	if (kof_find_str_all(scan_range_data, s0, s1)) {
		/* matcher 2: Default fingerprints of Diamorphine, open-source version. Very easy to bypass. */
		if (kof_find_str_any(scan_range_data, s2, s3, s4))
			KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
		KOF_SCAN_SUSPECT(KOF_MALVAR_GENERIC);
	}
}
