/*
 * Generated by KOFViewer.
 *
 * Test sample: 0b22cdc1b1b1f944e4ca8fced2e234d14aeeef830970e8ae7491cbdcb3e11460_detected_detected
 * Researcher:  dmknght
 * Created 2026-09-02, updated 2026-09-02
 * Engine:      db format 8, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_EXPLOIT, "DirtyCow");

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_HEXSTR(s0, "2F746D702F7061737377642E62616B00726F6F740025733A25733A25643A25643A25733A25733A2573");
KOF_DEFINE_STR(s1, "DON'T FORGET TO RESTORE! $ mv %s %s", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_all(scan_range_code, s0, s1))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
