/*
 * Generated by KOFViewer.
 *
 * Test sample: Trojan.Shell.Agent.jb-f61811f9cd70d6fb833b8a2992bb84aafeacc2e81dbc6ec3f846fcaa81bd2e60  sha256:f61811f9cd70d6fb833b8a2992bb84aa
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_SCRIPT);
KOF_TARGET_NAME(KOF_MALTYPE_DROPPER, "Error84");

KOF_TARGET_SUBTYPE(KOF_SCRIPT_SHELL);

KOF_TARGET_RANGE(scan_range_whole_file, KOF_SCAN_ALL);

KOF_DEFINE_STR(s0, "CRONLINE=\"*/5 * * * * /usr/bin/bash -c '", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_all(scan_range_whole_file, s0))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
