/*
 * Generated by KOFViewer.
 *
 * Test sample: Trojan.Shell.Agent.jc-bc268c7b8f16b8fdc992c5f32b3a0dbe29ec8411971a26d3dbe00d3cadc00479  sha256:977be16e07f7a5285719bb5876e3ebc6
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

/*
 * Check if PC uses Nvidia then executes dropper logic. Possibly deploy coin miner.
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_SCRIPT);
KOF_TARGET_NAME(KOF_MALTYPE_DROPPER, "LinShell");

KOF_TARGET_SUBTYPE(KOF_SCRIPT_SHELL);

KOF_TARGET_RANGE(scan_range_whole_file, KOF_SCAN_ALL);

KOF_DEFINE_STR(s0, "cd /tmp && bash <(wget http://", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);
KOF_DEFINE_STR(s1, "cd /tmp && curl -fsSL http://", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);
KOF_DEFINE_STR(s2, "if command -v nvidia-smi >/dev/null 2>&1; then", KOF_CASE_EXACT, KOF_WORD_TOKEN);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_all(scan_range_whole_file, s0, s1, s2))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
