/*
 * Generated by KOFViewer.
 *
 * Test sample: Backdoor.Shell.Agent corpus (624 samples reached)
 * Test sample: Backdoor.Shell.Agent.z-00b8b05ceb30191adfb617718c1b46b41aec022c57e64b774bc7dd7a9dc38c0d
 * Test sample: normalized:Backdoor.Shell.Agent.z-0ac17b5ec73932d1d3135ea38b0fc7dc598b3bb7941d32e0fb2160b882fdda8f
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

/*
 * FreePBX dropper: it writes a webshell over admin/views/ajax.php and then copies footer.php's timestamp onto it, so a listing of the directory shows nothing newer than the rest of the install.
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_SCRIPT);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "FpbxShell");

KOF_TARGET_SUBTYPE(KOF_SCRIPT_SHELL);

KOF_TARGET_RANGE(scan_range_whole_file, KOF_SCAN_ALL);

KOF_DEFINE_STR(s0, "useradd -s /bin/bash -ou 0 -g 0 -p", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "for user in $(ls /home); do userdel -rf \\\"$user\\\"; done", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_all(scan_range_whole_file, s0, s1))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
