/*
 * Generated by KOFViewer.
 *
 * Test sample: 793599165003c5f0cb774236db8c99554286b73d3b804b79f1f7b9864481f9fa
 * Researcher:  dmknght
 * Created 2026-08-31, updated 2026-08-31
 * Engine:      db format 6, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_HACKTOOL, "pnscan");

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_STR(s0, "This program implements a multithreaded TCP port scanner", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "<host-range> <port-range>", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_code, s0, s1))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
