/*
 * Generated by KOFViewer.
 *
 * Test sample: Trojan.Shell.Agent.in-933d5963dfb7307e87a193e32681b9d1a4a23bd2d0821b091930e2a9460aaf91
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_SCRIPT);
KOF_TARGET_NAME(KOF_MALTYPE_DROPPER, "LinShell");

KOF_TARGET_SUBTYPE(KOF_SCRIPT_SHELL);

KOF_TARGET_RANGE(scan_range_whole_file, KOF_SCAN_ALL);

KOF_DEFINE_STR(s0, "wget -qO /var/tmp/cliaarch", KOF_CASE_EXACT, KOF_WORD_TOKEN);
KOF_DEFINE_STR(s1, "curl -s -o /var/tmp/cliaarch", KOF_CASE_EXACT, KOF_WORD_TOKEN);
KOF_DEFINE_STR(s2, "/var/tmp/cliaarch start accept --token ", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_all(scan_range_whole_file, s0, s1, s2))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
