/*
 * Generated by KOFViewer.
 *
 * Test sample: shikata_ga_nai
 * Test sample: cleartext
 * Researcher:  dmknght
 * Created 2026-09-01, updated 2026-09-02
 * Engine:      db format 8, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "Meterp");

KOF_TARGET_ARCH(KOF_ARCH_X86_64);
KOF_TARGET_SUBTYPE(KOF_ELF_EXEC);

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_HEXSTR(s0, "6a 10 5a 6a 2a 58 0f 05 [8-15] 57 6a 23 58 6a 00 6a 05 48 89 e7 48 31 f6 0f 05");

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_code, s0))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
