/*
 * Generated by KOFViewer.
 *
 * Test sample: pe
 * Researcher:  dmknght
 * Created 2026-09-09, updated 2026-09-09
 * Engine:      db format 1.1, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_PE);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "Meterp");

KOF_TARGET_SUBTYPE(KOF_PE_DLL);

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_PE_CODE);

KOF_DEFINE_STR(s0, "MimikatzCustomCommand", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "PeinjectorInjectShellcode", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s2, "MeterpreterInvoke", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s3, "LanattacksAddTftpFile", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_code, s0, s1, s2, s3))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
