/*
 * Generated by KOFViewer.
 *
 * Test sample: shikata_ga_nai
 * Researcher:  dmknght
 * Created 2026-09-01, updated 2026-09-02
 * Engine:      db format 7, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "Meterp");

KOF_TARGET_SUBTYPE(KOF_ELF_EXEC);

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_HEXSTR(s0, "576A23586A006A054889E74831F60F05");

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_code, s0))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
