/*
 * Generated by KOFViewer.
 *
 * Test sample: win_x64_raw
 * Test sample: win_x64_clear
 * Researcher:  dmknght
 * Created 2026-09-02, updated 2026-09-02
 * Engine:      db format 8, module ABI 2
 */

/*
 * Win64 RAW (shellcode)
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_PE);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "Meterp");

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_PE_CODE);

KOF_DEFINE_HEXSTR(s0, "4885F675B441FFE7");

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_code, s0))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
