/*
 * Generated by KOFViewer.
 *
 * Test sample: win_x64_clear
 * Researcher:  dmknght
 * Created 2026-09-02, updated 2026-09-02
 * Engine:      db format 8, module ABI 2
 */

/*
 * windows/x64/meterpreter/reverse_tcp
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_PE);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "Meterp");

KOF_TARGET_RANGE(scan_range_data, KOF_SCAN_PE_DATA);
KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_PE_CODE);

KOF_DEFINE_STR(s0, "zzzdbg", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "PAYLOAD:", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s2, "VirtualProtect", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s3, "AXAX^YZAXAYAZH", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s4, "VirtualProtect", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_all(scan_range_data, s0, s1, s2))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
	else if (kof_find_str_all(scan_range_code, s3, s4))
		KOF_SCAN_SUSPECT(KOF_MALVAR_AUTO);
}
