/*
 * Generated by KOFViewer.
 *
 * Test sample: x86_clear
 * Researcher:  dmknght
 * Created 2026-09-02, updated 2026-09-02
 * Engine:      db format 8, module ABI 2
 */

/*
 * linux/x86/meterpreter/reverse_tcp
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "Meterp");

KOF_TARGET_ARCH(KOF_ARCH_X86);
KOF_TARGET_SUBTYPE(KOF_ELF_EXEC);

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_HEXSTR(s0, "B207B90010000089E3C1EB0CC1E30CB07DCD80 [6-12] B2??B003CD8085C07802FFE1");

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_code, s0))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
