/*
 * Generated by KOFViewer.
 *
 * Test sample: x64_rev_http_clear
 * Researcher:  dmknght
 * Created 2026-09-02, updated 2026-09-02
 * Engine:      db format 8, module ABI 2
 */

/*
 * linux/x64/meterpreter/reverse_http
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "Meterp");

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);
KOF_TARGET_RANGE(scan_range_noload, KOF_SCAN_ELF_NOLOAD);

KOF_DEFINE_STR(s0, "mettle_build_gem", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "MSF_LICENSE", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s2, "mettle_start", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_code, s0, s1))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
	else if (kof_find_str_any(scan_range_noload, s2))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
