/*
 * Generated by KOFViewer.
 *
 * Test sample: gminer
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_MINER, "gminer");

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_STR(s0, "GMiner", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);
KOF_DEFINE_STR(s1, "stratum", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s2, "ssl://", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_all(scan_range_code, s0, s1, s2))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
