/*
 * Generated by KOFViewer.
 *
 * Test sample: Trojan.Shell.Agent.jd-78e95ee51ec115dd1dae0085284544d08991b43a39a136e38f2d8fa618693ea8  sha256:78e95ee51ec115dd1dae0085284544d0
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_SCRIPT);
KOF_TARGET_NAME(KOF_MALTYPE_DROPPER, "Miner");

KOF_TARGET_SUBTYPE(KOF_SCRIPT_SHELL);

KOF_TARGET_RANGE(scan_range_whole_file, KOF_SCAN_ALL);

KOF_DEFINE_STR(s0, "for hf in /root/.bash_history /root/.zsh_history", KOF_CASE_EXACT, KOF_WORD_TOKEN);
KOF_DEFINE_STR(s1, "MINER_URL_BACKUP=\"", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s2, "MINER_URL_IP=\"", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_all(scan_range_whole_file, s0, s1, s2))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
