/*
 * Generated by KOFViewer.
 *
 * Test sample: f0e1cf0931162529d8ae1ede1e260824d58a04ae0a8bd44cb226c68eab91bc90.elf
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_STR(s0, " %*d: %64[0-9A-Fa-f]:%x %*s %x %*s %*s %*s %*s %*s %lu", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_all(scan_range_code, s0))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
