/*
 * Generated by KOFViewer.
 *
 * Test sample: 063830221431f8136766f2d740df6419c8cd2f73b10e07fa30067df506592210_detected_detected
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_STR(s0, "[0;31mSuccessfully Bruteforced IP: ", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "[0;31mPassword: ", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s2, "LOLNOGTFO", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_code, s0, s1, s2))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
