/*
 * Generated by KOFViewer.
 *
 * Test sample: bin.sh
 * Researcher:  dmknght
 * Created 2026-08-31, updated 2026-08-31
 * Engine:      db format 6, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_HEXSTR(s0, "2F70726F632F73656C662F636D646C696E650052756E6E004552520A00474554202F4D6F7A692E3620485454502F312E30");

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_code, s0))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
