/*
 * Generated by KOFViewer.
 *
 * Test sample: 0afd9f52ddada582d5f907e0a8620cbdbe74ea31cf775987a5675226c1b228c2_detected_detected
 * Test sample: bin.sh
 * Researcher:  dmknght
 * Created 2026-08-31, updated 2026-08-31
 * Engine:      db format 6, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Mirai");

KOF_TARGET_RANGE(scan_range_code_data, KOF_SCAN_ELF_CODE | KOF_SCAN_ELF_DATA);

KOF_DEFINE_STR(s0, "&dest_host=`", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "GET /shell", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_code_data, s0, s1))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
