/*
 * Generated by KOFViewer.
 *
 * Test sample: nbminer
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_MINER, "nbminer");

KOF_TARGET_RANGE(scan_range_data, KOF_SCAN_ELF_DATA);

KOF_DEFINE_STR(s0, "NBMiner", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "_ZN5Miner10signalStopEv", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_all(scan_range_data, s0, s1))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
