/*
 * Generated by KOFViewer.
 *
 * Test sample: 0
 * Researcher:  dmknght
 * Created 2026-09-12, updated 2026-09-12
 * Engine:      db format 1.1, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_ROOTKIT, "PoisonedFresh");

KOF_TARGET_SUBTYPE(KOF_ELF_DYN);

KOF_TARGET_RANGE(scan_range_sym_exp, KOF_SCAN_SYM_EXP);

KOF_DEFINE_HEXSTR(s0, "0101001561705F6861636B5F6170");

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_sym_exp, s0))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
