/*
 * Generated by KOFViewer.
 *
 * Test sample: 0
 * Researcher:  dmknght
 * Created 2026-09-12, updated 2026-09-12
 * Engine:      db format 1.1, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_ROOTKIT, "PoisonedFresh");

KOF_TARGET_SUBTYPE(KOF_ELF_DYN);

KOF_TARGET_RANGE(scan_range_noload, KOF_SCAN_ELF_NOLOAD);

KOF_DEFINE_STR(s0, "&FU:'", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_HEXSTR(s1, "980E4786FD377A585A");

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_all(scan_range_noload, s0, s1))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
