/*
 * Generated by KOFViewer.
 *
 * Test sample: 3b4e756212ea2ed01da98cceeb856449bb50d380339b5564e30cbe7fbfdae2d4
 */

/*
 * Unknown family. LD_PRELOAD rootkit. Strings are sym names.
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_ROOTKIT, "ProcHider");

KOF_TARGET_SUBTYPE(KOF_ELF_DYN);

KOF_TARGET_RANGE(scan_range_noload, KOF_SCAN_ELF_NOLOAD);

KOF_DEFINE_STR(s0, "process_to_filter", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "processhider", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s2, "original_readdir64", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s3, "original_readdir", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_all(scan_range_noload, s0, s1))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
	else if (kof_find_str_all(scan_range_noload, s2, s3))
		KOF_SCAN_SUSPECT(KOF_MALVAR_AUTO);
}
