/*
 * Generated by KOFViewer.
 *
 * Test sample: 3b4e756212ea2ed01da98cceeb856449bb50d380339b5564e30cbe7fbfdae2d4
 * Test sample: 87e8da015e2fc0937085411e59feb0c252d6e66fcb9d2bc526e57ae75c822eeb.elf
 * Researcher:  dmknght
 * Created 2026-09-28, updated 2026-09-28
 * Engine:      db format 2.0, module ABI 3
 */

/*
 * Unknown family. LD_PRELOAD rootkit. Reworked signature using SYM_EXP instead of old string way.
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_ROOTKIT, "ProcHider");

KOF_TARGET_SUBTYPE(KOF_ELF_DYN);

KOF_TARGET_RANGE(scan_range_sym_exp, KOF_SCAN_SYM_EXP);

KOF_DEFINE_HEXSTR(s0, "0400000170726F6365737368696465722E63", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_HEXSTR(s1, "0100001570726F636573735F746F5F66696C746572", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_HEXSTR(s2, "010000156F726967696E616C5F72656164646972");

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_sym_exp, s0, s1, s2))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
