/*
 * Generated by KOFViewer.
 *
 * Test sample: 0dcfa54a7e8a4e631ef466670ce604a61f3b0e8b3e9cf72c943278c0f77c31a2_detected_detected
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_MINER, "CoinMiner");

KOF_TARGET_RANGE(scan_range_code_data, KOF_SCAN_ELF_CODE | KOF_SCAN_ELF_DATA);

KOF_DEFINE_STR(s0, "Started Mining", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "Miner will restart", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s2, "Miner not responding", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s3, "stratum+ssl://", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s4, "stratum+tcp://", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s5, "daemon+https://", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s6, "daemon+http://", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s7, "xmr-stak", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s8, "xmrig.com", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s9, "xmrigMiner", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_code_data, s0, s1, s2))
		KOF_SCAN_SUSPECT(KOF_MALVAR_GENERIC);
	if (kof_find_str_any(scan_range_code_data, s3, s4, s5, s6))
		KOF_SCAN_INFECT(KOF_MALVAR_GENERIC);
	if (kof_find_str_any(scan_range_code_data, s7))
		KOF_SCAN_INFECT("XMRStak");
	if (kof_find_str_any(scan_range_code_data, s8, s9))
		KOF_SCAN_INFECT("Xmrig");
}
