/*
 * Generated by KOFViewer.
 *
 * Test sample: 0c8e384be26b7a2425acb12dcc2b75b35445735cc3c60837fc3536f6d3c8c8bc.bin.sample
 * Researcher:  dmknght
 * Created 2026-08-29, updated 2026-08-29
 * Engine:      db format 4, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "qbot");

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_STR(s0, "stdudpbasedflood", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "ParasJhaIsADumbFag", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s2, "stdflood4", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s3, "qbotbotnet", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s4, "miraiMIRAI", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_multi(scan_range_code, s0, s1, s2, s3, s4) >= 2)
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
