/*
 * Generated by KOFViewer.
 *
 * Test sample: hcrootkit_1.sample
 */

/*
 * Specific version on internet. There's no sample of latest variant on latest kernel.
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_ROOTKIT, "HCRootkit");

KOF_TARGET_SUBTYPE(KOF_ELF_REL);

KOF_TARGET_RANGE(scan_range_data, KOF_SCAN_ELF_DATA);

KOF_DEFINE_STR(s0, "sys_call_table", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "kallsyms_lookup_name", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s2, "sys_mmap", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s3, "sys_munmap", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s4, "sys_write", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_all(scan_range_data, s0, s1, s2, s3, s4))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
