/*
 * Generated by KOFViewer.
 *
 * Test sample: 060b01f15c7fab6c4f656aa1f120ebc1221a71bca3177f50083db0ed77596f0f
 * Researcher:  dmknght
 * Created 2026-08-29, updated 2026-08-29
 * Engine:      db format 4, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_ROOTKIT, "ldpre");

KOF_TARGET_SUBTYPE(KOF_ELF_DYN);

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_STR(s0, "is_invisible_with_pids", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_code, s0))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
