/*
 * Generated by KOFViewer.
 *
 * Researcher:  dmknght
 * Created 2026-09-22
 * Engine:      db format 8, module ABI 2
 */

/*
 * RST, build A - the /~telcom69/ command channel.
 *
 * The same family as rst_00.c and a different payload: block containment
 * between the two builds has a median of 8-9% and string containment a median
 * of 3%, measured payload against payload rather than object against object.
 * They share a lineage, not code.
 *
 *
 * WHERE THE PATTERN COMES FROM, AND WHY NOT FROM THE FRONT.
 *
 * The first 160 bytes after the entry are almost entirely different from
 * sample to sample, which is what made a first pass conclude this build had
 * no pattern at all. It has: 1655 CONSECUTIVE BYTES identical across all 62
 * samples, further in. The front varies and the body does not.
 *
 * And the body sits at a FIXED DISTANCE from the entry - 236 bytes in 61 of
 * the 62, and 232 in the remaining one - so it can be tested at a computed
 * offset rather than searched for.
 *
 *
 * TWO ANSWERS, AS IN rst_00.c.
 *
 *   AT entry + 236 - this object is a host that was patched, the entry is the
 *   start of the payload (60 of 62 have it outside every declared section),
 *   and the host's original entry is 34 bytes in. Located, so offered.
 *
 *   ELSEWHERE IN THE CODE - present, not located, not offered.
 *
 * THE SAVED ADDRESS IS CHECKED, not assumed: kof_u32 reads it and it has to
 * point below the entry, where the host is. One of the 62 carries no such
 * pointer at all and is reported without an offer, which is the right answer
 * for it.
 *
 * MEASURED: 217 objects of 2716 previously undetected - the same 217 a
 * similarity block over this payload found, which is why the block is not
 * here: identical reach, and no offset to repair from. 0 of 13159 clean
 * objects in /usr/bin and /usr/lib.
 */

#include <kofmod/kofsig.h>
#include <kofmod/elf.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_VIRUS, "RST");

KOF_TARGET_ARCH(KOF_ARCH_X86);

KOF_TARGET_RANGE(r_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_HEXSTR(s0, "75 16 46 47 49 81 f9 00 00 00 00 77 ed b8 01 00 "
		      "00 00 5f 5e 5a 59 5b c3 b8 00 00 00 00 5f 5e 5a");

void kof_scan(const struct kof_obj_ctx *ctx)
{
	const struct kof_elf_info *e = kof_elf(ctx);

	if (kof_find_str_at(ctx->entry_off + 236u, s0)) {
		uint64_t orig = kof_u32(ctx->entry_off + 34u);

		if (e && orig && orig < e->entry_addr)
			KOF_SCAN_CURABLE(ctx->entry_off);
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
	}
	if (kof_find_str_any(r_code, s0))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}



/*
 * PUTTING IT BACK.
 *
 * THE SHAPE OF THE DAMAGE, which took two wrong repairs to establish and is
 * written down here so a third does not have to. The payload is in TWO
 * places, and neither of them is "appended to the end":
 *
 *     0     .. entry      the host
 *     entry .. 13480      payload, in the GAP a linker leaves between the end
 *                         of the text segment and the file offset the data
 *                         segment starts at. The virus did not grow the file
 *                         for this part; it grew p_filesz to cover it.
 *     13480 .. shoff      the host's own data and its remaining sections,
 *                         untouched and at their original offsets
 *     shoff .. shoff+tab  the section header table, untouched
 *     after the table     the rest of the payload, appended
 *
 * So nothing in the middle has moved and no offset in the file is stale. The
 * repair is three changes and not one of them shifts anything:
 *
 *   e_entry           back to the address the virus saved thirty-four bytes into its
 *                     own stub, so that it could return there.
 *   p_filesz, p_memsz  of the segment holding the entry, back down to where
 *                     the host's own bytes ended. The payload is then inside
 *                     the file and inside no segment, which is what a loader
 *                     reads as "not there".
 *   the file ends      after the section header table, dropping the appended
 *                     half.
 *
 * WHAT THE FIRST TWO ATTEMPTS GOT WRONG, because the correction is the
 * interesting part. Truncating at the entry threw away the section table,
 * which lives AFTER the payload's first half: the result reported
 * SHOFF_PAST_EOF and SECTAB_MISSING and the engine's own heuristic called it
 * Truncated. Cutting the range from the entry to e_shoff and moving e_shoff
 * down recovered the table and still left SEG_PAST_EOF and SEC_PAST_EOF,
 * because it was excising bytes that were never inserted - the gap was
 * already there. Measured on the repaired file, this version leaves no
 * anomaly at all and the engine reports it clean.
 *
 * NOTHING IS WRITTEN HERE. Every change is described and the host decides -
 * see kof_content.cure_patch. The bounds are the host's.
 */
void kof_cure(const struct kof_obj_ctx *ctx)
{
	uint64_t orig = kof_u32(ctx->entry_off + 34u);
	uint64_t phoff = kof_u32(28u);
	uint64_t shoff = kof_u32(32u);
	uint32_t phent = kof_u16(42u), phnum = kof_u16(44u);
	uint32_t shent = kof_u16(46u), shnum = kof_u16(48u);
	uint8_t b[4];
	uint32_t i;

	if (!phoff || !shoff || !phnum || !shnum)
		return;

	b[0] = (uint8_t)orig;
	b[1] = (uint8_t)(orig >> 8);
	b[2] = (uint8_t)(orig >> 16);
	b[3] = (uint8_t)(orig >> 24);
	kof_cure_patch(24u, b, 4u);

	/* The loadable segment the entry falls in, shrunk to where the host's
	 * own bytes ended. PT_LOAD is 1; p_offset is at 4, p_filesz at 16 and
	 * p_memsz at 20 of a 32-bit program header. */
	for (i = 0; i < phnum; i++) {
		uint64_t e = phoff + (uint64_t)i * phent;
		uint64_t off, fsz, keep;

		if (kof_u32(e) != 1u)
			continue;
		off = kof_u32(e + 4u);
		fsz = kof_u32(e + 16u);
		if (ctx->entry_off < off || ctx->entry_off >= off + fsz)
			continue;
		keep = ctx->entry_off - off;
		b[0] = (uint8_t)keep;
		b[1] = (uint8_t)(keep >> 8);
		b[2] = (uint8_t)(keep >> 16);
		b[3] = (uint8_t)(keep >> 24);
		kof_cure_patch(e + 16u, b, 4u);
		kof_cure_patch(e + 20u, b, 4u);
		break;
	}

	kof_cure_truncate(shoff + (uint64_t)shent * shnum);
}
