/*
 * Generated by KOFViewer.
 *
 * Researcher:  dmknght
 * Created 2026-09-22
 * Engine:      db format 8, module ABI 2
 */

/*
 * RST, build B - the shifted-strings one.
 *
 * WHAT THE FAMILY DOES. The payload is appended and the entry point is
 * redirected into it; the host is whatever executable was to hand - measured
 * here: ps, netstat, sshd, syslogd, inetd, ifconfig, with file sizes from
 * 8.5 KB to 583 KB. The tool names are in the HOST half of every sample and
 * in none of the payloads, so they are the programs that were infected and
 * not a target list the virus carries.
 *
 * THE STUB, which is the whole rule:
 *
 *     b8 ?? ?? 04 08   mov  eax, 0x0804????   the HOST'S ORIGINAL ENTRY
 *     60               pusha
 *     e8 19 0a 00 00   call <the virus body>
 *     61               popa
 *     ff e0            jmp  eax               back into the host
 *
 * Two bytes vary and they are the low half of that address. Measured: 157 of
 * the first 160 payload bytes are identical across all twenty samples.
 *
 *
 * WHY THIS AND NOT A SIMILARITY BLOCK.
 *
 * A block was written first and measured against this. It found 21 objects
 * where the pattern finds 22, and - the reason it was dropped - it cannot
 * lead anywhere: kof_plague_score answers with a PERCENTAGE. A repair needs
 * an offset, and a percentage has none. The pattern found at a known place
 * says both that the family is here and where its payload begins.
 *
 *
 * TWO ANSWERS, AND ONLY ONE OF THEM CAN BE REPAIRED.
 *
 *   AT THE ENTRY - this object IS a host that was patched. The address the
 *   program used to start at is still in the file, one byte into the stub, so
 *   the damage is located and KOF_SCAN_CURABLE says so.
 *
 *   ELSEWHERE IN THE CODE - the payload is present and nothing was redirected
 *   into it. Reported, and nothing is offered: there is no host to restore
 *   and no offset anybody established.
 *
 * Measured over the corpus: 22 of 22 objects carrying the stub carry it at
 * the entry, exactly once, and all 22 sit in KOF_SCAN_ELF_CODE - so the
 * region cannot tell the two apart and the entry point can.
 *
 * AND THE SAVED ADDRESS IS CHECKED BEFORE IT IS BELIEVED. kof_u32 reads it
 * and it has to point BELOW the entry, which is where the host is. A stub
 * whose saved address points into the payload or nowhere is not something to
 * offer a repair for, however well the bytes matched.
 *
 * MEASURED: 22 objects of 2716 previously undetected; 0 of 13159 clean
 * objects in /usr/bin and /usr/lib.
 */

#include <kofmod/kofsig.h>
#include <kofmod/elf.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_VIRUS, "RST");

KOF_TARGET_ARCH(KOF_ARCH_X86);

/* The payload lands in the code region in every sample measured, so that is
 * the only region searched - the file's data, headers and unclaimed tail
 * cannot hold it and cost a pass each. */
KOF_TARGET_RANGE(r_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_HEXSTR(s0, "b8 ?? ?? 04 08 60 e8 19 0a 00 00 61 ff e0 89 f6 "
		      "55 89 e5 eb 03 58 eb 42", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	const struct kof_elf_info *e = kof_elf(ctx);

	if (kof_find_str_at(ctx->entry_off, s0)) {
		uint64_t orig = kof_u32(ctx->entry_off + 1u);

		if (e && orig && orig < e->entry_addr)
			KOF_SCAN_CURABLE(ctx->entry_off);
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
	}
	if (kof_find_str_any(r_code, s0))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}



/*
 * PUTTING IT BACK.
 *
 * THE SHAPE OF THE DAMAGE, which took two wrong repairs to establish and is
 * written down here so a third does not have to. The payload is in TWO
 * places, and neither of them is "appended to the end":
 *
 *     0     .. entry      the host
 *     entry .. 13480      payload, in the GAP a linker leaves between the end
 *                         of the text segment and the file offset the data
 *                         segment starts at. The virus did not grow the file
 *                         for this part; it grew p_filesz to cover it.
 *     13480 .. shoff      the host's own data and its remaining sections,
 *                         untouched and at their original offsets
 *     shoff .. shoff+tab  the section header table, untouched
 *     after the table     the rest of the payload, appended
 *
 * So nothing in the middle has moved and no offset in the file is stale. The
 * repair is three changes and not one of them shifts anything:
 *
 *   e_entry           back to the address the virus saved one bytes into its
 *                     own stub, so that it could return there.
 *   p_filesz, p_memsz  of the segment holding the entry, back down to where
 *                     the host's own bytes ended. The payload is then inside
 *                     the file and inside no segment, which is what a loader
 *                     reads as "not there".
 *   the file ends      after the section header table, dropping the appended
 *                     half.
 *
 * WHAT THE FIRST TWO ATTEMPTS GOT WRONG, because the correction is the
 * interesting part. Truncating at the entry threw away the section table,
 * which lives AFTER the payload's first half: the result reported
 * SHOFF_PAST_EOF and SECTAB_MISSING and the engine's own heuristic called it
 * Truncated. Cutting the range from the entry to e_shoff and moving e_shoff
 * down recovered the table and still left SEG_PAST_EOF and SEC_PAST_EOF,
 * because it was excising bytes that were never inserted - the gap was
 * already there. Measured on the repaired file, this version leaves no
 * anomaly at all and the engine reports it clean.
 *
 * NOTHING IS WRITTEN HERE. Every change is described and the host decides -
 * see kof_content.cure_patch. The bounds are the host's.
 */
void kof_cure(const struct kof_obj_ctx *ctx)
{
	uint64_t orig = kof_u32(ctx->entry_off + 1u);
	uint64_t phoff = kof_u32(28u);
	uint64_t shoff = kof_u32(32u);
	uint32_t phent = kof_u16(42u), phnum = kof_u16(44u);
	uint32_t shent = kof_u16(46u), shnum = kof_u16(48u);
	uint8_t b[4];
	uint32_t i;

	if (!phoff || !shoff || !phnum || !shnum)
		return;

	b[0] = (uint8_t)orig;
	b[1] = (uint8_t)(orig >> 8);
	b[2] = (uint8_t)(orig >> 16);
	b[3] = (uint8_t)(orig >> 24);
	kof_cure_patch(24u, b, 4u);

	/* The loadable segment the entry falls in, shrunk to where the host's
	 * own bytes ended. PT_LOAD is 1; p_offset is at 4, p_filesz at 16 and
	 * p_memsz at 20 of a 32-bit program header. */
	for (i = 0; i < phnum; i++) {
		uint64_t e = phoff + (uint64_t)i * phent;
		uint64_t off, fsz, keep;

		if (kof_u32(e) != 1u)
			continue;
		off = kof_u32(e + 4u);
		fsz = kof_u32(e + 16u);
		if (ctx->entry_off < off || ctx->entry_off >= off + fsz)
			continue;
		keep = ctx->entry_off - off;
		b[0] = (uint8_t)keep;
		b[1] = (uint8_t)(keep >> 8);
		b[2] = (uint8_t)(keep >> 16);
		b[3] = (uint8_t)(keep >> 24);
		kof_cure_patch(e + 16u, b, 4u);
		kof_cure_patch(e + 20u, b, 4u);
		break;
	}

	kof_cure_truncate(shoff + (uint64_t)shent * shnum);
}
