/*
 * Generated by KOFViewer.
 *
 * Test sample: 280cbd451329655c0bb9ee30730b556cf5e3b307bafa482d2bf129d388cc9ed5_detected_detected
 * Test sample: 2d8e89b1febe64a6c35ec2fbbe1535bca4a0f4744f560e9737a17050e66cd6a6_detected_detected
 * Researcher:  dmknght
 * Created 2026-09-02, updated 2026-09-02
 * Engine:      db format 8, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "SCLoader");

KOF_TARGET_RANGE(scan_range_data_noload, KOF_SCAN_ELF_DATA | KOF_SCAN_ELF_NOLOAD);
KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_STR(s0, "Shellcode Length: %d", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "shellcode2.c", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_HEXSTR(s2, "488D05ED2E0000488945F8488B55F8B800000000FFD2");

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_data_noload, s0, s1))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
	else if (kof_find_str_any(scan_range_code, s2))
		KOF_SCAN_SUSPECT(KOF_MALVAR_AUTO);
}
