/*
 * Generated by KOFViewer.
 *
 * Test sample: 4d10236d246bceeb7a8834c9a2f0f4e2184174d81eda5585ea405d7d1c53c635_detected_detected
 * Researcher:  dmknght
 * Created 2026-09-02, updated 2026-09-02
 * Engine:      db format 8, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "SCLoader");

KOF_TARGET_RANGE(scan_range_noload, KOF_SCAN_ELF_NOLOAD);

KOF_DEFINE_HEXSTR(s0, "007368656C6C636F646500");

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_noload, s0))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
