/*
 * Generated by KOFViewer.
 *
 * Test sample: Shellcode
 * Test sample: VirusShare_d5dc2c0ca3b55dc6e81298944929e61b
 * Researcher:  dmknght
 * Created 2026-09-05, updated 2026-09-12
 * Engine:      db format 1.1, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "Shellcode");

KOF_TARGET_RANGE(scan_range_data, KOF_SCAN_ELF_DATA);

KOF_DEFINE_STR(s0, "Ph//shh/bin", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (ctx->obj_size > 40960ull)
		return;

	if (kof_find_str_any(scan_range_data, s0))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
