/*
 * Generated by KOFViewer.
 *
 * Test sample: 33b7c82fc836f11ec1bfbca088b3e5243ca6bf74c081f1f17319103f30de097b
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "StoneD");

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_STR(s0, "ByStoneD", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "Fazla Soket", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_all(scan_range_code, s0, s1))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
