/*
 * Generated by KOFViewer.
 *
 * Test sample: 0
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "TeamTNT");

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_STR(s0, "HildeGardTeamTNT", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "[ connect_back_host ]", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_code, s0, s1))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
