/*
 * Generated by KOFViewer.
 *
 * Test sample: 0
 * Test sample: 136e41fccb8c901ac58d35da7aac10f2eb40df10cd032273fc98143275585d5e
 * Researcher:  dmknght
 * Created 2026-08-29, updated 2026-08-29
 * Engine:      db format 4, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "TeamTNT");

KOF_TARGET_RANGE(scan_range_code_data, KOF_SCAN_ELF_CODE | KOF_SCAN_ELF_DATA);

KOF_DEFINE_STR(s0, "HildeGardTeamTNT", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "[ connect_back_host ]", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_code_data, s0, s1))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
