/*
 * Generated by KOFViewer.
 *
 * Test sample: HEUR-Backdoor.Linux.Agent.gen-a57edcd75708383acc728a3925c032c3480f496f6a86a7e9a15e64ae07a05ea9  sha256:a57edcd75708383acc728a39
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 3
 */

/*
 * Exploit redis to deploy reverse sehll
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "RedisRouge");

KOF_TARGET_RANGE(scan_range_data, KOF_SCAN_ELF_DATA);

KOF_DEFINE_STR(s0, "revshell forked to %s", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_HEXSTR(s1, "2F62696E2F7368002D69002F62696E2F62617368006F6F6D0073797374656D2829", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_data, s0, s1))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
