/*
 * Generated by KOFViewer.
 *
 * Test sample: 0:NORMALIZED  sha256:a0f36938228fe4a8f8bb4cfa9099774013742b1a4dd99e2d6f0997e2f5000699
 * Researcher:  dmknght
 * Created 2026-09-16, updated 2026-09-17
 * Engine:      db format 1.1, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_SCRIPT);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "Webshell");

KOF_TARGET_SUBTYPE(KOF_SCRIPT_ASP);

KOF_TARGET_RANGE(scan_range_whole_file, KOF_SCAN_ALL);

KOF_DEFINE_STR(s0, "Server.CreateObject(\"WScript.Shell\")", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "objWShell.Exec(command)", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_all(scan_range_whole_file, s0, s1))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
