/*
 * Generated by KOFViewer.
 *
 * Test sample: 0  sha256:4b27c0f9862d4cca8479f471246d7c9d013ab1f9fbf99e33dc82592e50791083
 * Researcher:  dmknght
 * Created 2026-09-22, updated 2026-09-22
 * Engine:      db format 1.1, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "Merlin");

KOF_TARGET_RANGE(scan_range_data, KOF_SCAN_ELF_DATA);
KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_HEXSTR(s0, "132A6167656E742E6D65726C696E436C69656E74", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);
KOF_DEFINE_HEXSTR(s1, "B85368656C6C636F644839030F", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);
KOF_DEFINE_HEXSTR(s2, "10657865637574655368656C6C636F6465", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);
KOF_DEFINE_STR(s3, "Executing shellcode %s", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_multi(scan_range_data, s0, s2, s3) >= 2 || kof_find_str_any(scan_range_code, s1))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
