/*
 * Generated by KOFViewer.
 *
 * Test sample: 0  sha256:5cefa61fb3c9130c3396a3735674f075dcf7fd226c262eaa485b4dc69333ba23
 * Researcher:  dmknght
 * Created 2026-09-19, updated 2026-09-19
 * Engine:      db format 1.1, module ABI 2
 */

/*
 * x86 only. X64 showed incompatible payload
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_PE);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "Meterp");

KOF_TARGET_ARCH(KOF_ARCH_X86);

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_PE_CODE);

KOF_DEFINE_HEXSTR(s0, "648B52308B520C8B5214", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);
KOF_DEFINE_HEXSTR(s1, "C1CF0D01C74975EF", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);
KOF_DEFINE_HEXSTR(s2, "6A 40 68 00 10 00 00 56 6A 00 68 [4] FF D5", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);
KOF_DEFINE_HEXSTR(s3, "01 C3 29 C6 75 ?? C3", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_all(scan_range_code, s0, s1, s2, s3))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
