/*
 * Generated by KOFViewer.
 *
 * Test sample: aspx_bypass_av.aspx
 * Test sample: cmdasp.aspx  sha256:5f959f480a66a33d37d9a0ef6c8f7d0059625ca2a8ae9236b49b194733622655
 * Test sample: 0:NORMALIZED  sha256:70890ac82e46927a6b6b52526245b5a6759af849ca496e9a0ffb49ef3eae9651
 * Researcher:  dmknght
 * Created 2026-09-16, updated 2026-09-17
 * Engine:      db format 1.1, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_SCRIPT);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "Webshell");

KOF_TARGET_SUBTYPE(KOF_SCRIPT_ASPX);

KOF_TARGET_RANGE(scan_range_whole_file, KOF_SCAN_ALL);

KOF_DEFINE_STR(s0, "ASPX Webshell bypass AV", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, ".RedirectStandardOutput=true;", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);
KOF_DEFINE_STR(s2, "Process.Start(", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);
KOF_DEFINE_HEXSTR(s3, "2E 41 72 67 75 6D 65 6E 74 73 3D 22 2F (63|43) 20 22", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);
KOF_DEFINE_HEXSTR(s4, "2E 46 69 6C 65 4E 61 6D 65 3D 22 (63|43) (6D|4D) (64|44) 2E (65|45) (78|58) (65|45) 22 3B", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	/* matcher 1: Threat Actor's fingerprint */
	if (kof_find_str_any(scan_range_whole_file, s0))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
	/* matcher 2: Execute cmd */
	if (kof_find_str_all(scan_range_whole_file, s1, s2, s3, s4))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
