/*
 * Generated by KOFViewer.
 *
 * Test sample: 5083be49c4a8cb03dad57c64bfa402c3e1afedadfaeb38430d47fa71f0e7bccd
 * Test sample: 72b86cf168181480d745b27f57ef574c8d6208daf36c898eddd0700f41f8a03d
 * Researcher:  dmknght
 * Created 2026-08-29, updated 2026-08-30
 * Engine:      db format 6, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_VIRUS, "Tsunami");

KOF_TARGET_RANGE(scan_range_code_data, KOF_SCAN_ELF_CODE | KOF_SCAN_ELF_DATA);

KOF_DEFINE_STR(s0, "/tmp/.python", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "NOTICE %s :Bot by anonymous", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s2, "TSUNAMI <target> <secs>", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s3, "Tsunami heading for %s", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s4, "syn flooder", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s5, "udp flooder", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s6, "c4k.xpl", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	/* matcher 1: Suspicious: common strings flooder */
	if (kof_find_str_any(scan_range_code_data, s1, s4, s5))
		KOF_SCAN_SUSPECT(KOF_MALVAR_AUTO);
	else if (kof_find_str_any(scan_range_code_data, s0, s2, s3, s6))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
