/*
 * Generated by KOFViewer.
 *
 * Test sample: c8aeb927cd1b897a9c31199f33a6df9f297707bed1aa0e66d167270f1fde6ff5_detected_detected
 * Researcher:  dmknght
 * Created 2026-08-29, updated 2026-08-29
 * Engine:      db format 6, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "Tsunami");

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_HEXSTR(s0, "47 45 54 20 2F [4-7] 2E 74 73 75 6E 61 6D 69");
KOF_DEFINE_STR(s1, "Tsunami successfully deployed", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_code, s0, s1))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
