/*
 * Generated by KOFViewer.
 *
 * Test sample: normalized:HEUR-Backdoor.Linux.Mirai.b-036f5b0ccd595315d4c10fca45bca7fcbb786d93b01c42d5b979bc5d45c02d46
 * Test sample: HEUR-Backdoor.Linux.Mirai.b-036f5b0ccd595315d4c10fca45bca7fcbb786d93b01c42d5b979bc5d45c02d46
 * Researcher:  dmknght
 * Created 2026-09-26, updated 2026-09-26
 * Engine:      db format 2.0, module ABI 4
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_ELF);
KOF_TARGET_NAME(KOF_MALTYPE_BOTNET, "VapeBot");

KOF_TARGET_RANGE(scan_range_code, KOF_SCAN_ELF_CODE);

KOF_DEFINE_STR(s0, "VapeBot/Locker", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, "VapeBot has been executed", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	/* matcher 1: +0xd245, 6871 bytes, 128 hash(es) */
	if (kof_find_str_any(scan_range_code, s0, s1))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
