/*
 * Generated by KOFViewer.
 *
 * Test sample: 0:NORMALIZED  sha256:c8aca2c93ecd8957437fa5035e46ad2c94acf5a70d95307f916979c49648231a
 * Researcher:  dmknght
 * Created 2026-09-17, updated 2026-09-17
 * Engine:      db format 1.1, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_SCRIPT);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "Webshell");

KOF_TARGET_SUBTYPE(KOF_SCRIPT_PHP);

KOF_TARGET_RANGE(scan_range_whole_file, KOF_SCAN_ALL);

KOF_DEFINE_STR(s0, "eval(base64_decode(", KOF_CASE_EXACT, KOF_WORD_FULLWORD);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_whole_file, s0))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
