/*
 * Generated by KOFViewer.
 *
 * Test sample: newaspcmd.asp
 * Test sample: 0:NORMALIZED  sha256:63d300297fb07398350fff6732727573da13dd7ab9c82d2a3cf1ece561b7215f
 * Researcher:  dmknght
 * Created 2026-09-16, updated 2026-09-18
 * Engine:      db format 1.1, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_SCRIPT);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "Webshell");

KOF_TARGET_SUBTYPE(KOF_SCRIPT_ASP);

KOF_TARGET_RANGE(scan_range_whole_file, KOF_SCAN_ALL);

KOF_DEFINE_STR(s0, "objShell=CreateObject(\"WScript.Shell\")", KOF_CASE_EXACT, KOF_WORD_TOKEN);
KOF_DEFINE_STR(s1, "objCmdExec=objshell.exec(", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);
KOF_DEFINE_STR(s2, "getCommandOutput(\"cmd /c\"", KOF_CASE_EXACT, KOF_WORD_TOKEN);
KOF_DEFINE_STR(s3, "objCmdExec.StdOut.ReadAll", KOF_CASE_EXACT, KOF_WORD_TOKEN);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_whole_file, s0) && kof_find_str_any(scan_range_whole_file, s1, s2, s3))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
