/*
 * Generated by KOFViewer.
 *
 * Test sample: 0:NORMALIZED
 * Researcher:  dmknght
 * Created 2026-09-16, updated 2026-09-16
 * Engine:      db format 1.1, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_SCRIPT);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "Webshell");

KOF_TARGET_SUBTYPE(KOF_SCRIPT_ASP);

KOF_TARGET_RANGE(scan_range_body, KOF_SCAN_SCRIPT_BODY);

KOF_DEFINE_STR(s0, "ActiveXObject(\"WScript.Shell\");", KOF_CASE_EXACT, KOF_WORD_TOKEN);
KOF_DEFINE_STR(s1, "shell.Exec(\"%comspec%", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_all(scan_range_body, s0, s1))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
