/*
 * Generated by KOFViewer.
 *
 * Test sample: aspx_bypass_av.aspx
 * Researcher:  dmknght
 * Created 2026-09-16, updated 2026-09-16
 * Engine:      db format 1.1, module ABI 2
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_SCRIPT);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "Webshell");

KOF_TARGET_SUBTYPE(KOF_SCRIPT_ASPX);

KOF_TARGET_RANGE(scan_range_whole_file, KOF_SCAN_ALL);

KOF_DEFINE_STR(s0, "ASPX Webshell bypass AV", KOF_CASE_EXACT, KOF_WORD_FULLWORD);
KOF_DEFINE_STR(s1, ".FileName = \"cmd.exe\";", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);
KOF_DEFINE_STR(s2, ".Arguments = \"/C \"", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);
KOF_DEFINE_STR(s3, ".RedirectStandardOutput = true;", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);
KOF_DEFINE_STR(s4, "Process.Start(", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	/* matcher 1: Threat Actor's fingerprint */
	if (kof_find_str_any(scan_range_whole_file, s0))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
	/* matcher 2: Execute cmd */
	else if (kof_find_str_all(scan_range_whole_file, s1, s2, s3, s4))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
