/*
 * Generated by KOFViewer.
 *
 * Test sample: haha.php
 * Researcher:  dmknght
 * Created 2026-09-15, updated 2026-09-15
 * Engine:      db format 1.1, module ABI 2
 */

/*
 * weevely generate -obfuscator cleartext1_php
 */

#include <kofmod/kofsig.h>

KOF_TARGET_FORMAT(KOF_FMT_SCRIPT);
KOF_TARGET_NAME(KOF_MALTYPE_TROJAN, "Weevely");

KOF_TARGET_SUBTYPE(KOF_SCRIPT_PHP);

KOF_TARGET_RANGE(scan_range_body, KOF_SCAN_SCRIPT_BODY);

KOF_DEFINE_STR(s0, "@eval(@gzuncompress(@", KOF_CASE_EXACT, KOF_WORD_SUBSTRING);

void kof_scan(const struct kof_obj_ctx *ctx)
{
	if (kof_find_str_any(scan_range_body, s0))
		KOF_SCAN_INFECT(KOF_MALVAR_AUTO);
}
