/*
 * x86_diff - the x86 decoder against a reference decoder, on random encodings.
 *
 * A DEV TOOL, NOT A TEST: it needs the reference decoder's headers and library,
 * which are not in this tree. `make genotype-x86-diff REF=<dir>` builds and runs it.
 *
 * The tables are generated by asking the reference, so this can only say "the same
 * as the reference" - it would pass with a bug both share. tests/unit/genotype_x86.c
 * holds the encodings written from the manuals, which is the other half.
 *
 * Deterministic: a fixed seed, so a failure is the same failure tomorrow. It builds
 * legacy encodings with random prefixes and opcodes, and VEX / EVEX / XOP encodings
 * with random payloads, in both modes, and compares validity, length, identity,
 * operand count and every field of every operand.
 *
 * NOT COMPARED: REX2, the APX forms of EVEX and the 3DNow! suffix map are not
 * decoded (see x86.h), so a case the reference reads as one of them is skipped.
 * A short list of families where the reference refuses combinations this decoder
 * accepts (MPX, complex FP16, gathers, a few EVEX conversions) is listed by name,
 * counted and capped; a divergence in any OTHER instruction fails the run.
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>

#include "bddisasm.h"
#include "x86/x86.h"

static int failures;

static void ok(const char *what, int cond)
{
	if (!cond) {
		printf("  FAIL %s\n", what);
		failures++;
	}
}

/* ---- the differential half ------------------------------------------------ */

static uint64_t rs;

static uint32_t rnd(void)
{
	rs ^= rs << 13;
	rs ^= rs >> 7;
	rs ^= rs << 17;
	return (uint32_t)(rs >> 11);
}

static const uint8_t PFX[] = { 0x66, 0x67, 0xf0, 0xf2, 0xf3, 0x2e, 0x36, 0x3e, 0x26, 0x64, 0x65 };

static int is_prefix(uint8_t b)
{
	size_t i;

	for (i = 0; i < sizeof PFX; i++)
		if (PFX[i] == b)
			return 1;
	return 0;
}

/* The reference read this as something this decoder does not decode. */
static int not_decoded(const INSTRUX *ix, const uint8_t *p)
{
	if (ix->HasRex2)
		return 1;
	if (ix->HasEvex) {
		unsigned q = 0;

		while (is_prefix(p[q]))
			q++;
		if (ix->EvexMode || (p[q + 1] & 8) || !(p[q + 2] & 4))
			return 1;
	}
	return p[ix->PrefLength] == 0x0f && p[ix->PrefLength + 1] == 0x0f;
}

/*
 * THE FAMILIES THE REFERENCE REFUSES IN MORE CASES THAN THIS DECODER DOES - see
 * the head of the file. Matched on the reference's identity when it decoded the
 * bytes, on this decoder's when it did not.
 */
static int known_divergence(unsigned id)
{
	switch (id) {
	case GT_X86_I_BNDMOV: case GT_X86_I_BNDLDX: case GT_X86_I_BNDSTX:
	case GT_X86_I_BNDMK: case GT_X86_I_BNDCL: case GT_X86_I_BNDCU:
	case GT_X86_I_BNDCN:
	case GT_X86_I_UMONITOR: case GT_X86_I_RMPUPDATE:
	case GT_X86_I_VCVTSD2USI: case GT_X86_I_VCVTSS2SI: case GT_X86_I_VCVTSS2USI:
	case GT_X86_I_VCVTSD2SI:
	case GT_X86_I_VFCMADDCPH: case GT_X86_I_VFCMADDCSH: case GT_X86_I_VFCMULCPH:
	case GT_X86_I_VFCMULCSH: case GT_X86_I_VFMADDCPH: case GT_X86_I_VFMADDCSH:
	case GT_X86_I_VFMULCPH: case GT_X86_I_VFMULCSH:
	case GT_X86_I_VGATHERDPD: case GT_X86_I_VGATHERDPS: case GT_X86_I_VGATHERQPD:
	case GT_X86_I_VGATHERQPS: case GT_X86_I_VPGATHERDD: case GT_X86_I_VPGATHERDQ:
	case GT_X86_I_VPGATHERQD: case GT_X86_I_VPGATHERQQ:
	case GT_X86_I_VSCATTERDPD: case GT_X86_I_VSCATTERDPS: case GT_X86_I_VSCATTERQPD:
	case GT_X86_I_VSCATTERQPS: case GT_X86_I_VPSCATTERDD: case GT_X86_I_VPSCATTERDQ:
	case GT_X86_I_VPSCATTERQD: case GT_X86_I_VPSCATTERQQ:
	case GT_X86_I_ENQCMD: case GT_X86_I_ENQCMDS: case GT_X86_I_MOVDIR64B:
		return 1;
	}
	return 0;
}

/* Why two decodes of the same bytes differ, or 0. */
static const char *differ(const INSTRUX *ix, const struct gt_x86_insn *x)
{
	struct gt_x86_op ops[GT_X86_MAX_OPS];
	unsigned i;

	if (ix->Length != x->len)
		return "length";
	if ((unsigned)ix->Instruction != x->id)
		return "identity";
	if (ix->OperandsCount != gt_x86_nops(x))
		return "operand count";
	if (ix->Condition != gt_x86_cond(x))
		return "condition";
	if (ix->Rep != x->rep)
		return "rep";
	gt_x86_operands(x, ops);
	for (i = 0; i < ix->OperandsCount; i++) {
		const ND_OPERAND *o = &ix->Operands[i];
		const struct gt_x86_op *d = &ops[i];

		if (o->Type != d->type)
			return "operand type";
		if ((o->Size == 0xffffffffu ? 0xffffu : o->Size) != d->size)
			return "operand size";
		if (o->Access.Access != d->acc)
			return "access";
		if (o->Flags.Flags != d->flags)
			return "operand flags";
		switch (o->Type) {
		case ND_OP_REG:
			if (o->Info.Register.Type != d->rtype || o->Info.Register.Reg != d->reg)
				return "register";
			if (o->Info.Register.Size != d->rsize)
				return "register size";
			if (o->Info.Register.IsHigh8 != d->high8)
				return "high byte register";
			if (o->Info.Register.Count != d->count)
				return "register count";
			break;
		case ND_OP_MEM: {
			const ND_OPDESC_MEMORY *m = &o->Info.Memory;
			unsigned f = (m->IsStack ? 1 : 0) | (m->IsString ? 2 : 0) | (m->IsDirect ? 4 : 0) |
				     (m->IsAG ? 8 : 0) | (m->IsBitbase ? 16 : 0) | (m->IsMib ? 32 : 0) |
				     (m->IsVsib ? 64 : 0) | (m->IsShadowStack ? 128 : 0);

			if (m->HasBase != !!(d->mf & GT_X86_M_BASE) ||
			    (m->HasBase && (m->Base != d->base || m->BaseSize != d->bsz)))
				return "memory base";
			if (m->HasIndex != !!(d->mf & GT_X86_M_INDEX) ||
			    (m->HasIndex && (m->Index != d->index || m->IndexSize != d->isz ||
					     m->Scale != d->scale)))
				return "memory index";
			if (m->HasDisp != !!(d->mf & GT_X86_M_DISP) ||
			    (m->HasDisp && (int64_t)m->Disp * (m->HasCompDisp ? (int64_t)m->CompDispSize : 1) != d->v))
				return "memory displacement";
			if (m->HasSeg != !!(d->mf & GT_X86_M_SEG) || (m->HasSeg && m->Seg != d->seg))
				return "memory segment";
			if (m->IsRipRel != !!(d->mf & GT_X86_M_RIPREL) || f != (unsigned)(d->mf >> 8) % 256u)
				return "memory kind";
			break;
		}
		case ND_OP_IMM: {
			uint64_t a = o->Info.Immediate.Imm, b = (uint64_t)d->v;

			if (o->Size < 8) {
				const uint64_t mask = (1ull << (8 * o->Size)) - 1u;

				a &= mask;
				b &= mask;
			}
			if (a != b || o->Info.Immediate.RawSize != d->rawsize)
				return "immediate";
			break;
		}
		case ND_OP_OFFS:
			if ((int64_t)o->Info.RelativeOffset.Rel != d->v)
				return "relative offset";
			break;
		case ND_OP_ADDR:
			if (o->Info.Address.Offset != (uint64_t)d->v || o->Info.Address.BaseSeg != d->sel)
				return "far address";
			break;
		case ND_OP_CONST:
			if (o->Info.Constant.Const != (uint64_t)d->v)
				return "constant";
			break;
		}
	}
	return NULL;
}

static unsigned build_case(uint8_t *b)
{
	unsigned n = 0, w = rnd() & 1u, np = rnd() % 4u, i, ext = rnd() % 4u;

	b[n++] = (uint8_t)w;                        /* the mode travels in byte 0 */
	for (i = 0; i < np; i++)
		b[n++] = PFX[rnd() % sizeof PFX];
	if (ext == 0) {
		unsigned m = rnd() % 8u;

		if (w && (rnd() & 1u))
			b[n++] = (uint8_t)(0x40 | (rnd() & 15u));
		if (m < 3) {
			b[n++] = (uint8_t)rnd();
		} else if (m < 6) {
			b[n++] = 0x0f;
			b[n++] = (uint8_t)rnd();
		} else if (m == 6) {
			b[n++] = 0x0f;
			b[n++] = 0x38;
			b[n++] = (uint8_t)rnd();
		} else {
			b[n++] = 0x0f;
			b[n++] = 0x3a;
			b[n++] = (uint8_t)rnd();
		}
	} else {
		unsigned kind = rnd() % 4u;

		if (!w && kind == 2)
			kind = 0;
		if (kind == 0) {
			b[n++] = 0xc5;
			b[n++] = (uint8_t)rnd();
		} else if (kind == 1) {
			b[n++] = 0xc4;
			b[n++] = (uint8_t)((rnd() & 0xe0) | (1 + rnd() % 3));
			b[n++] = (uint8_t)rnd();
		} else if (kind == 2) {
			b[n++] = 0x62;
			b[n++] = (uint8_t)((rnd() & 0xf0) | ((rnd() % 3 == 0) ? 5 + rnd() % 2 : 1 + rnd() % 3));
			b[n++] = (uint8_t)(rnd() | 4);
			b[n++] = (uint8_t)rnd();
		} else {
			b[n++] = 0x8f;
			b[n++] = (uint8_t)((rnd() & 0xe0) | (8 + rnd() % 3));
			b[n++] = (uint8_t)rnd();
		}
		b[n++] = (uint8_t)rnd();
	}
	while (n < 20)
		b[n++] = (rnd() % 5 == 0) ? 0 : (uint8_t)rnd();
	return n;
}

#define CASES 3000000u

static void differential(void)
{
	unsigned long k, agree = 0, skipped = 0, known = 0, bad = 0;
	const char *first_why = NULL;
	uint8_t first[24];

	printf("differential against the reference decoder (%u cases):\n", CASES);
	rs = 0x9e3779b97f4a7c15ull;
	for (k = 0; k < CASES; k++) {
		uint8_t buf[32];
		const uint8_t *p;
		int w;
		INSTRUX ix;
		struct gt_x86_insn x;
		NDSTATUS s;
		enum gt_status gs;
		const char *why = NULL;
		unsigned id;

		build_case(buf);
		w = buf[0];
		p = buf + 1;
		s = NdDecodeEx(&ix, p, 16, w ? ND_CODE_64 : ND_CODE_32, w ? ND_DATA_64 : ND_DATA_32);
		gs = gt_x86_decode(&x, p, 16, w ? 64 : 32);
		id = ND_SUCCESS(s) ? (unsigned)ix.Instruction : gs == GT_OK ? x.id : 0u;
		if (ND_SUCCESS(s)) {
			if (not_decoded(&ix, p)) {
				skipped++;
				continue;
			}
			why = gs != GT_OK ? "valid for the reference, refused here" : differ(&ix, &x);
		} else if (gs == GT_OK) {
			why = "refused by the reference, accepted here";
		}
		if (!why) {
			agree++;
		} else if (known_divergence(id)) {
			known++;
		} else {
			bad++;
			if (!first_why) {
				first_why = why;
				memcpy(first, buf, sizeof first);
			}
		}
	}
	printf("    agree %lu, skipped (not decoded) %lu, known divergence %lu, other %lu\n",
	       agree, skipped, known, bad);
	if (first_why) {
		unsigned i;

		printf("    first other: %s, %d-bit:", first_why, first[0] ? 64 : 32);
		for (i = 1; i < 17; i++)
			printf(" %02x", first[i]);
		printf("\n");
	}
	ok("no divergence outside the listed families", bad == 0);
	/* The list is not a license: if it grows past a few hundredths of a percent
	 * something has broken that the list is now hiding. */
	ok("the listed families stay rare", known < CASES / 2000u);
}

int main(void)
{
	printf("x86 differential:\n");
	ok("identities are the reference's",
	   GT_X86_I_ADD == ND_INS_ADD && GT_X86_I_MOV == ND_INS_MOV &&
	   GT_X86_I_CALLNR == ND_INS_CALLNR && GT_X86_I_VADDPS == ND_INS_VADDPS);
	differential();
	printf("x86 differential: %s\n", failures ? "FAILED" : "ok");
	return failures != 0;
}
