/*
 * plague_object - a similarity rule, from source to verdict.
 *
 * plague_match proves the matcher against inputs built beside it. This proves
 * the PATH: KOF_PLAGUE_BLOCK read out of tests/sigs/plague, hashes carried through
 * ksigbuilder into a pack, loaded and rebased into the engine's table, indexed,
 * counted by the prepass, and read back by a rule through kof_plague_score.
 *
 * Every one of those steps can be wrong in a way that produces no error and no
 * finding - a rebase that forgot to add a base, a section the loader validated
 * and never read, a prepass that fed the wrong region. A rule that silently
 * never fires looks exactly like one that works, which is why this test exists
 * rather than an inspection of the pack.
 *
 * THE BLOCK IS THE ONE tests/sigs/plague/fixture_00.c CARRIES, and the bytes are
 * generated by the same named sequence the rule's hashes were taken from. If
 * the generator here and the one that produced those hashes ever disagree, this
 * test fails - which is the point: the hashes in that file are the only copy.
 */

#define _POSIX_C_SOURCE 200809L

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../../libkofeng/kofeng.h"

static int failures;

static void fail(const char *what, const char *why)
{
	printf("  FAIL %s: %s\n", what, why);
	failures++;
}

#define BLK 4096u

static uint32_t rnd(uint32_t *s)
{
	*s ^= *s << 13; *s ^= *s >> 17; *s ^= *s << 5;
	return *s;
}

static void make_block(uint8_t *b)
{
	uint32_t s = 0xC0FFEEu, i;

	for (i = 0; i < BLK; i++)
		b[i] = (uint8_t)rnd(&s);
}

struct seen {
	int objects;
	int hit;
	/* Which verdict this scan is counting - the file holds more than one
	 * rule now, and each case is about its own. */
	const char *want;
};

static int on_object(const char *name, const void *bytes, uint64_t len,
		     const struct kof_result *res, void *user)
{
	struct seen *s = user;
	uint32_t i;

	(void)name; (void)bytes; (void)len;
	s->objects++;
	if (!res)
		return 0;
	for (i = 0; i < res->n; i++)
		if (strstr(res->v[i].name, s->want))
			s->hit++;
	return 0;
}

static int scan_named(struct kof_engine *eng, const uint8_t *p, size_t n,
		      const char *want)
{
	struct kof_scan_option opt;
	struct kof_scanner *sc = kof_scanner_new(eng);
	struct seen s;

	if (!sc)
		return -1;
	memset(&s, 0, sizeof s);
	s.want = want;
	memset(&opt, 0, sizeof opt);
	/*
	 * EVERY RULE THAT FIRES, not the first one.
	 *
	 * A scan stops at the first finding by default, and the ELF below
	 * carries two rules on purpose - one declared over the whole object and
	 * one declared in the headers. Without this the second was never
	 * reached and read as the engine having gone silent about it, which is
	 * a fault in the test and not in the pass it is about.
	 */
	opt.all_matches = 1;
	if (kof_scan_bytes(sc, p, n, "fixture.bin", &opt, on_object, &s) <= 0)
		s.hit = -1;
	kof_scanner_free(sc);
	return s.hit;
}

static int scan_it(struct kof_engine *eng, const uint8_t *p, size_t n)
{
	return scan_named(eng, p, n, "KofengPlagueFixture");
}

/*
 * WHERE THE PREPASS LOOKS, which is not the same question as what the matcher
 * counts.
 *
 * Two rules over the same ELF, declared differently. KOF_SCAN_ALL names no
 * region, so the pass that serves it walks the object's regions and leaves out
 * the ones nothing is ever cut from - and it must still reach a block sitting
 * in NOLOAD, which is one of the two regions that walk gates for padding.
 * KOF_SCAN_ELF_HEADERS is the other half of the same rule: the headers are left
 * out of the walk, and a block that NAMES them must be looked for there anyway.
 *
 * Both were silent for different reasons at different points in the day - the
 * first when a missing region was read as matching nothing, the second when
 * headers were skipped wherever they appeared.
 */
static void elf_paths(struct kof_engine *eng)
{
	static uint8_t buf[1u << 20];
	FILE *f = fopen("build/test/fixtures/plain-elf64", "rb");
	size_t n;

	if (!f) {
		printf("  (no plain-elf64 fixture - the region walk is not "
		       "tested)\n");
		return;
	}
	n = fread(buf, 1, sizeof buf, f);
	fclose(f);
	if (!n)
		return;
	if (scan_named(eng, buf, n, "AnyRegion") <= 0)
		fail("whole-object block", "a block declared KOF_SCAN_ALL did "
		     "not reach NOLOAD, where it was cut from");
	if (scan_named(eng, buf, n, "InHeader") <= 0)
		fail("header block", "a block that names the header region was "
		     "not looked for there");
}

int main(int argc, char **argv)
{
	/* The TEST signature tree, not the shipped one: this rule exists to
	 * prove the path and has no business in bases/ - see tests/sigs. */
	const char *db = argc > 1 ? argv[1] : "build/test/databases-sigs";
	static uint8_t blk[BLK], hay[BLK * 3];
	struct kof_engine *eng;
	int r;

	setvbuf(stdout, NULL, _IONBF, 0);
	make_block(blk);

	eng = kof_engine_open(db);
	if (!eng) {
		printf("plague object: no database at %s - nothing tested\n", db);
		return 0;
	}

	/* whole */
	memset(hay, 0xA5, sizeof hay);
	memcpy(hay + BLK, blk, BLK);
	r = scan_it(eng, hay, sizeof hay);
	if (r < 0)
		fail("scan", "the object was not scanned at all");
	else if (r == 0)
		fail("whole block", "the rule did not fire on the block it "
		     "was written from - somewhere between the source and the "
		     "prepass the hashes stopped arriving");

	/*
	 * DAMAGED, AND IT MUST STILL FIRE. The rule asks for fifty percent; a
	 * quarter overwritten leaves about seventy-five. A build where this
	 * passes and the whole case fails would mean the score is being
	 * computed but not read; one where this fails and the whole case
	 * passes would mean the rule is an exact match wearing a percentage.
	 */
	memset(hay, 0xA5, sizeof hay);
	memcpy(hay + BLK, blk, BLK);
	memset(hay + BLK, 0x00, BLK / 4u);
	if (scan_it(eng, hay, sizeof hay) == 0)
		fail("damaged block", "a quarter overwritten and the rule went "
		     "silent, though it asks for half");

	/* absent */
	memset(hay, 0x5A, sizeof hay);
	if (scan_it(eng, hay, sizeof hay) > 0)
		fail("absent block", "the rule fired on bytes that do not "
		     "contain it");

	elf_paths(eng);

	kof_engine_close(eng);
	if (failures) {
		printf("plague object: %d check(s) failed\n", failures);
		return 1;
	}
	printf("plague object: a block declared in tests/sigs/plague reaches a "
	       "verdict through the pack, the loader and the prepass - whole, "
	       "damaged, absent, over the whole object and in the headers - "
	       "ok\n");
	return 0;
}
